import type { FlightInputCaseId } from '@tests/front/ui/scene/flight-input.cases';

export type FlightInputMutation = Readonly<{
  id: string;
  file: string;
  find: string;
  replace: string;
  nth?: number;
  caseIds: readonly FlightInputCaseId[];
}>;

const INPUT = 'src/scene/input/flight-input.ts';
const STICK = 'src/scene/input/stick.ts';

export const FLIGHT_INPUT_MUTATIONS: readonly FlightInputMutation[] = [
  {
    id: 'key.enabled-ignored',
    file: INPUT,
    find: 'if (!enabled || isEditable(event.target)',
    replace: 'if (isEditable(event.target)',
    caseIds: ['input.key.enabled'],
  },
  {
    id: 'key.editable-ignored',
    file: INPUT,
    find: 'isEditable(event.target) || ',
    replace: '',
    caseIds: ['input.key.editable'],
  },
  {
    id: 'key.meta-ignored',
    file: INPUT,
    find: 'event.metaKey || ',
    replace: '',
    caseIds: ['input.key.modifiers'],
  },
  {
    id: 'key.ctrl-ignored',
    file: INPUT,
    find: 'event.ctrlKey || ',
    replace: '',
    caseIds: ['input.key.modifiers'],
  },
  {
    id: 'key.alt-ignored',
    file: INPUT,
    find: ' || event.altKey',
    replace: '',
    caseIds: ['input.key.modifiers'],
  },
  {
    id: 'key.shift-dropped',
    file: INPUT,
    find: '      keys.add(event.code);\n\n      return;',
    replace: '      return;',
    caseIds: ['input.key.steer'],
  },
  {
    id: 'key.filter-dropped',
    file: INPUT,
    find: '    if (!FLIGHT_KEY_CODES.has(event.code)) {\n      return;\n    }\n\n',
    replace: '',
    caseIds: ['input.key.prevent', 'input.first'],
  },
  {
    id: 'key.first-input-dropped',
    file: INPUT,
    find: '    keys.add(event.code);\n    noteInput();',
    replace: '    keys.add(event.code);',
    caseIds: ['input.first'],
  },
  {
    id: 'key.always-prevent',
    file: INPUT,
    find: 'if (!insideSurface(event.target)) {',
    replace: 'if (true) {',
    caseIds: ['input.key.prevent'],
  },
  {
    id: 'key.never-prevent',
    file: INPUT,
    find: '      event.preventDefault();\n',
    replace: '',
    caseIds: ['input.key.prevent'],
  },
  {
    id: 'key.keyup-dropped',
    file: INPUT,
    find: '    keys.delete(event.code);\n',
    replace: '',
    caseIds: ['input.key.steer'],
  },
  {
    id: 'key.blur-keys-kept',
    file: INPUT,
    find: '    keys.clear();\n',
    replace: '',
    caseIds: ['input.key.blur', 'input.key.enabled'],
  },
  {
    id: 'key.blur-boost-kept',
    file: INPUT,
    find: '    boostHeld = false;\n    stick.release();',
    replace: '    stick.release();',
    caseIds: ['input.key.blur', 'input.key.enabled'],
  },
  {
    id: 'key.disable-stick-kept',
    file: INPUT,
    find: '    boostHeld = false;\n    stick.release();',
    replace: '    boostHeld = false;',
    caseIds: ['input.key.enabled'],
  },
  {
    id: 'key.disable-no-release',
    file: INPUT,
    find: '      if (!value) {\n        releaseAll();\n      }\n',
    replace: '',
    caseIds: ['input.key.enabled'],
  },
  {
    id: 'boost.ignored',
    file: INPUT,
    find: '      boostHeld = held;\n',
    replace: '',
    caseIds: ['input.boost'],
  },
  {
    id: 'first.repeats',
    file: INPUT,
    find: '    if (used) {\n      return;\n    }\n\n',
    replace: '',
    caseIds: ['input.first'],
  },
  {
    id: 'first.stick-dropped',
    file: INPUT,
    find: '    if (stick.press(event)) {\n      noteInput();\n    }',
    replace: '    stick.press(event);',
    caseIds: ['input.first-stick'],
  },
  {
    id: 'pointer.button-any',
    file: INPUT,
    find: "(event.pointerType === 'mouse' && event.button !== 0)",
    replace: 'false',
    caseIds: ['stick.buttons'],
  },
  {
    id: 'pointer.disabled-ignored',
    file: INPUT,
    find: '    if (!enabled || (event.pointerType',
    replace: '    if ((event.pointerType',
    caseIds: ['input.key.enabled'],
  },
  {
    id: 'dispose.keydown',
    file: INPUT,
    find: "      window.removeEventListener('keydown', onKeyDown);\n",
    replace: '',
    caseIds: ['input.dispose'],
  },
  {
    id: 'dispose.keyup',
    file: INPUT,
    find: "      window.removeEventListener('keyup', onKeyUp);\n",
    replace: '',
    caseIds: ['input.dispose'],
  },
  {
    id: 'dispose.blur',
    file: INPUT,
    find: "      window.removeEventListener('blur', releaseAll);\n",
    replace: '',
    caseIds: ['input.dispose'],
  },
  {
    id: 'dispose.pointerdown',
    file: INPUT,
    find: "      canvas.removeEventListener('pointerdown', onPointerDown);\n",
    replace: '',
    caseIds: ['input.dispose'],
  },
  {
    id: 'stick.press-hidden',
    file: STICK,
    find: '    elements.root.hidden = false;\n',
    replace: '',
    caseIds: ['stick.press'],
  },
  {
    id: 'stick.origin',
    file: STICK,
    find: 'translate(${originX - radius}px',
    replace: 'translate(${originX}px',
    caseIds: ['stick.press'],
  },
  {
    id: 'stick.origin-y',
    file: STICK,
    find: '${originY - radius}px',
    replace: '${originY}px',
    caseIds: ['stick.press'],
  },
  {
    id: 'stick.clamp',
    file: STICK,
    find: 'if (length > radius) {',
    replace: 'if (length > radius * 2) {',
    caseIds: ['stick.clamp'],
  },
  {
    id: 'stick.release-hidden',
    file: STICK,
    find: '    elements.root.hidden = true;\n',
    replace: '',
    caseIds: ['stick.release'],
  },
  {
    id: 'stick.release-state',
    file: STICK,
    find: '    state.active = false;\n    state.dx = 0;\n    state.dy = 0;\n',
    replace: '',
    caseIds: ['stick.release'],
  },
  {
    id: 'stick.cancel-dropped',
    file: STICK,
    find: "  window.addEventListener('pointercancel', onEnd);\n",
    replace: '',
    caseIds: ['stick.release'],
  },
  {
    id: 'stick.move-any-pointer',
    file: STICK,
    find: '    if (event.pointerId !== pointerId) {\n      return;\n    }\n\n    let dx',
    replace: '    let dx',
    caseIds: ['stick.buttons'],
  },
  {
    id: 'stick.end-any-pointer',
    file: STICK,
    find: 'if (event.pointerId === pointerId) {\n      release();',
    replace: 'if (true) {\n      release();',
    caseIds: ['stick.buttons'],
  },
  {
    id: 'stick.second-press',
    file: STICK,
    find: '    if (pointerId !== NO_POINTER) {\n      return false;\n    }\n\n',
    replace: '',
    caseIds: ['stick.buttons'],
  },
  {
    id: 'stick.move-on-canvas',
    file: STICK,
    find: "window.addEventListener('pointermove', onMove);",
    replace: "canvas.addEventListener('pointermove', onMove);",
    caseIds: ['stick.capture-fallback'],
  },
  {
    id: 'stick.end-on-canvas',
    file: STICK,
    find: "window.addEventListener('pointerup', onEnd);",
    replace: "canvas.addEventListener('pointerup', onEnd);",
    caseIds: ['stick.capture-fallback'],
  },
  {
    id: 'stick.capture-throws',
    file: STICK,
    find: '    } catch {\n      return false;\n    }',
    replace: '    } catch (error) {\n      throw error;\n    }',
    caseIds: ['stick.capture-fallback'],
  },
  {
    id: 'stick.redundant-write',
    file: STICK,
    find: '    if (dx === state.dx && dy === state.dy) {\n      return;\n    }\n\n',
    replace: '',
    caseIds: ['stick.no-redundant-writes'],
  },
  {
    id: 'stick.dispose-move',
    file: STICK,
    find: "      window.removeEventListener('pointermove', onMove);\n",
    replace: '',
    caseIds: ['input.dispose'],
  },
  {
    id: 'stick.dispose-up',
    file: STICK,
    find: "      window.removeEventListener('pointerup', onEnd);\n",
    replace: '',
    caseIds: ['input.dispose'],
  },
  {
    id: 'stick.dispose-cancel',
    file: STICK,
    find: "      window.removeEventListener('pointercancel', onEnd);\n",
    replace: '',
    caseIds: ['input.dispose'],
  },
  {
    id: 'stick.dispose-capture',
    file: STICK,
    find: "      canvas.removeEventListener('lostpointercapture', onEnd);\n",
    replace: '',
    caseIds: ['input.dispose'],
  },
];
