import type { RuntimeCaseId } from '@tests/back/scene/runtime/runtime.cases';

export type RuntimeMutation = Readonly<{
  id: string;
  file: string;
  find: string;
  replace: string;
  nth?: number;
  caseIds: readonly RuntimeCaseId[];
}>;

const GATE = 'src/scene/runtime/loop-gate.ts';
const QUALITY = 'src/scene/runtime/quality.ts';
const CONSTANTS = 'src/scene/runtime/runtime.constants.ts';
const EFFECTS = 'src/scene/runtime/effects.ts';
const RIG = 'src/scene/runtime/camera-rig.ts';
const CONTROLLER = 'src/scene/runtime/world-controller.ts';
const LOOP = 'src/scene/runtime/frame-loop.ts';
const LOADER = 'src/scene/runtime/world-message.ts';
const PIXEL = 'src/scene/visuals/pixel-texture.ts';
const TERRAIN = 'src/scene/visuals/terrain.ts';

export const RUNTIME_MUTATIONS: readonly RuntimeMutation[] = [
  {
    id: 'gate.ignores-view',
    file: GATE,
    find: "input.view === 'world' && ",
    replace: '',
    caseIds: ['gate.stops.text-view', 'gate.table.single-true'],
  },
  {
    id: 'gate.ignores-boot',
    file: GATE,
    find: "input.bootStatus === 'running'",
    replace: "input.bootStatus !== 'idle'",
    caseIds: ['gate.stops.before-take-off', 'gate.table.single-true'],
  },
  {
    id: 'gate.ignores-hidden',
    file: GATE,
    find: '!input.hidden && ',
    replace: '',
    caseIds: ['gate.stops.hidden', 'gate.table.single-true'],
  },
  {
    id: 'gate.ignores-context',
    file: GATE,
    find: ' && !input.contextLost',
    replace: '',
    caseIds: ['gate.stops.context-lost', 'gate.table.single-true'],
  },
  {
    id: 'profile.inclusive',
    file: QUALITY,
    find: 'width > NARROW_MAX_WIDTH',
    replace: 'width >= NARROW_MAX_WIDTH',
    caseIds: ['quality.profile.narrow'],
  },
  {
    id: 'dpr.uncapped',
    file: QUALITY,
    find: 'return Math.min(device, DPR_CAP[profile]);',
    replace: 'return device;',
    caseIds: ['quality.dpr.desktop-cap', 'quality.dpr.narrow-cap', 'quality.dpr.tier-one-keeps'],
  },
  {
    id: 'dpr.desktop-cap',
    file: CONSTANTS,
    find: 'desktop: 1.75, narrow: 1.5',
    replace: 'desktop: 2, narrow: 1.5',
    caseIds: ['quality.dpr.desktop-cap', 'quality.dpr.tier-one-keeps'],
  },
  {
    id: 'dpr.tier-one-drops',
    file: CONSTANTS,
    find: 'LOWEST_TIER = 2',
    replace: 'LOWEST_TIER = 1',
    caseIds: ['quality.dpr.tier-one-keeps', 'fps.sequence.slow-last'],
  },
  {
    id: 'dpr.cap-max',
    file: QUALITY,
    find: 'Math.min(device, DPR_CAP[profile])',
    replace: 'Math.max(device, DPR_CAP[profile])',
    caseIds: ['quality.dpr.below-cap', 'quality.dpr.desktop-cap'],
  },
  {
    id: 'tier.initial',
    file: QUALITY,
    find: 'INITIAL_TIER: Tier = 0',
    replace: 'INITIAL_TIER: Tier = 1',
    caseIds: ['quality.tier.initial', 'fps.sequence.slow-last'],
  },
  {
    id: 'bloom.narrow',
    file: QUALITY,
    find: "profile === 'desktop' && tier === 0",
    replace: 'tier === 0',
    caseIds: ['quality.bloom.desktop-tier-zero'],
  },
  {
    id: 'fps.no-grace',
    file: CONSTANTS,
    find: 'FPS_GRACE_MS = 2000',
    replace: 'FPS_GRACE_MS = 0',
    caseIds: [
      'fps.decline.two-windows',
      'fps.grace.ignored',
      'fps.consecutive.only',
      'fps.floor.by-profile',
      'fps.sequence.slow-last',
      'fps.restart.grace',
    ],
  },
  {
    id: 'fps.one-window',
    file: CONSTANTS,
    find: 'FPS_SLOW_WINDOWS = 2',
    replace: 'FPS_SLOW_WINDOWS = 1',
    caseIds: ['fps.decline.two-windows', 'fps.consecutive.only'],
  },
  {
    id: 'fps.not-consecutive',
    file: QUALITY,
    find: 'slowWindows = slow ? slowWindows + 1 : 0;',
    replace: 'slowWindows = slow ? slowWindows + 1 : slowWindows;',
    caseIds: ['fps.consecutive.only'],
  },
  {
    id: 'fps.desktop-floor',
    file: CONSTANTS,
    find: 'FPS_FLOOR = { desktop: 45, narrow: 26 }',
    replace: 'FPS_FLOOR = { desktop: 26, narrow: 26 }',
    caseIds: ['fps.floor.by-profile'],
  },
  {
    id: 'fps.narrow-floor',
    file: CONSTANTS,
    find: 'FPS_FLOOR = { desktop: 45, narrow: 26 }',
    replace: 'FPS_FLOOR = { desktop: 45, narrow: 45 }',
    caseIds: ['fps.floor.by-profile'],
  },
  {
    id: 'fps.never-slow',
    file: QUALITY,
    find: "exhausted = true;\n\n    return 'slow';",
    replace: "return 'hold';",
    caseIds: ['fps.sequence.slow-last'],
  },
  {
    id: 'fps.restart-noop',
    file: QUALITY,
    find: 'graceStart = nowMs;\n    windowStart = null;',
    replace: 'windowStart = null;',
    caseIds: ['fps.restart.grace'],
  },
  {
    id: 'effects.ring-idle',
    file: EFFECTS,
    find: 'ring: { t: 1,',
    replace: 'ring: { t: 0,',
    caseIds: ['effects.initial'],
  },
  {
    id: 'effects.dock-beam',
    file: CONSTANTS,
    find: 'DOCK_EFFECT = { beam: 2.6',
    replace: 'DOCK_EFFECT = { beam: 2',
    caseIds: ['effects.dock.values', 'controller.dock.effects'],
  },
  {
    id: 'effects.ring-lift',
    file: CONSTANTS,
    find: 'RING_LIFT = 0.15',
    replace: 'RING_LIFT = 0',
    caseIds: ['effects.dock.values'],
  },
  {
    id: 'effects.send-station',
    file: CONSTANTS,
    find: 'SEND_STATION = 8',
    replace: 'SEND_STATION = 0',
    caseIds: ['effects.send.values', 'controller.send.flash'],
  },
  {
    id: 'effects.send-shake',
    file: CONSTANTS,
    find: 'shake: 0.6 }',
    replace: 'shake: 0.35 }',
    caseIds: ['effects.send.values'],
  },
  {
    id: 'effects.take-off',
    file: CONSTANTS,
    find: 'TAKE_OFF_BLOOM = 0.6',
    replace: 'TAKE_OFF_BLOOM = 0.7',
    caseIds: ['effects.take-off.bloom'],
  },
  {
    id: 'effects.per-frame-decay',
    file: EFFECTS,
    find: 'return perFrame ** (dt * 60);',
    replace: 'return perFrame;',
    caseIds: ['effects.decay.rate-independent'],
  },
  {
    id: 'effects.bloom-decay',
    file: CONSTANTS,
    find: 'bloom: 0.94',
    replace: 'bloom: 0.9',
    caseIds: ['effects.decay.one-frame', 'effects.decay.rate-independent'],
  },
  {
    id: 'effects.no-cutoff',
    file: EFFECTS,
    find: 'if (effects.shake < SHAKE_MIN) {',
    replace: 'if (effects.shake < 0) {',
    caseIds: ['effects.shake.cutoff'],
  },
  {
    id: 'effects.ring-unclamped',
    file: EFFECTS,
    find: 'Math.min(1, effects.ring.t + step / SCENE_TIMING.ringSeconds)',
    replace: 'effects.ring.t + step / SCENE_TIMING.ringSeconds',
    caseIds: ['effects.ring.duration'],
  },
  {
    id: 'effects.burst-end',
    file: CONSTANTS,
    find: 'BURST_END = 1.2',
    replace: 'BURST_END = 1',
    caseIds: ['effects.initial', 'effects.burst.duration'],
  },
  {
    id: 'view.offset-sign',
    file: RIG,
    find: 'return { x: -VIEW_OFFSET * width, y: 0 };',
    replace: 'return { x: VIEW_OFFSET * width, y: 0 };',
    caseIds: ['view.offset.desktop', 'view.offset.boundary', 'view.offset.camera'],
  },
  {
    id: 'view.offset-narrow',
    file: RIG,
    find: 'return { x: 0, y: VIEW_OFFSET * height };',
    replace: 'return { x: 0, y: 0 };',
    caseIds: ['view.offset.narrow', 'view.offset.boundary'],
  },
  {
    id: 'view.boundary',
    file: RIG,
    find: 'if (width <= NARROW_MAX_WIDTH) {',
    replace: 'if (width < NARROW_MAX_WIDTH) {',
    caseIds: ['view.offset.boundary'],
  },
  {
    id: 'view.no-offset',
    file: RIG,
    find: 'camera.setViewOffset(width, height, offset.x, offset.y, width, height);',
    replace: '',
    caseIds: ['view.offset.camera'],
  },
  {
    id: 'camera.ease-linear',
    file: RIG,
    find: 'return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;',
    replace: 'return t;',
    caseIds: ['camera.ease'],
  },
  {
    id: 'camera.kick-reduced',
    file: RIG,
    find: 'if (reducedMotion) {\n    return 0;\n  }',
    replace: '',
    caseIds: ['camera.fov-kick'],
  },
  {
    id: 'camera.kick-unclamped',
    file: RIG,
    find: 'Math.min(1, Math.max(0, (speed - CRUISE_SPEED) / CRUISE_SPEED))',
    replace: '((speed - CRUISE_SPEED) / CRUISE_SPEED)',
    caseIds: ['camera.fov-kick'],
  },
  {
    id: 'camera.reduced-rate',
    file: CONSTANTS,
    find: 'CAMERA_POS_RATE = { normal: 4, reduced: 12 }',
    replace: 'CAMERA_POS_RATE = { normal: 4, reduced: 4 }',
    caseIds: ['camera.follow.rates'],
  },
  {
    id: 'camera.intro-from',
    file: CONSTANTS,
    find: 'INTRO_FROM = { x: -30, y: 90, z: 60 }',
    replace: 'INTRO_FROM = { x: -30, y: 60, z: 60 }',
    caseIds: ['camera.intro.start'],
  },
  {
    id: 'camera.no-floor',
    file: RIG,
    find: 'if (position.y < floor) {',
    replace: 'if (position.y < floor - 100) {',
    caseIds: ['camera.floor'],
  },
  {
    id: 'controller.no-visited',
    file: CONTROLLER,
    find: "return addVisited(setFlight(state, { mode: 'docked', station: id }), id);",
    replace: "return setFlight(state, { mode: 'docked', station: id });",
    caseIds: ['controller.dock.store'],
  },
  {
    id: 'controller.no-track',
    file: CONTROLLER,
    find: "deps.track({ name: 'station_docked', station: id });",
    replace: '',
    caseIds: ['controller.dock.track-once'],
  },
  {
    id: 'controller.effects-under-reduced',
    file: CONTROLLER,
    find: 'if (!reducedMotion) {\n        triggerDock(effects, event.station, stations);\n      }',
    replace: 'triggerDock(effects, event.station, stations);',
    caseIds: ['controller.dock.reduced'],
  },
  {
    id: 'controller.no-chime',
    file: CONTROLLER,
    find: 'audio.chime(event.station, 0);',
    replace: '',
    caseIds: ['controller.dock.sound', 'controller.dock.reduced'],
  },
  {
    id: 'controller.take-off-ignores-ready',
    file: CONTROLLER,
    find: "if (store.getSnapshot().boot.status === 'ready') {",
    replace: 'if (false) {',
    caseIds: ['controller.take-off.ready'],
  },
  {
    id: 'controller.no-undock-blip',
    file: CONTROLLER,
    find: 'audio.blip(false);',
    replace: '',
    caseIds: ['controller.take-off.undock'],
  },
  {
    id: 'controller.autopilot-index',
    file: CONTROLLER,
    find: "command({ type: 'autopilot', station: stationIndex(worldCommand.station) });",
    replace: "command({ type: 'autopilot', station: stationIndex(worldCommand.station) - 1 });",
    caseIds: ['controller.autopilot.mapping'],
  },
  {
    id: 'controller.no-flash',
    file: CONTROLLER,
    find: 'store.update(flashSend);',
    replace: '',
    caseIds: ['controller.send.flash'],
  },
  {
    id: 'controller.flash-under-reduced',
    file: CONTROLLER,
    find: 'if (!reducedMotion) {\n      triggerSend(effects, stations);',
    replace: 'if (true) {\n      triggerSend(effects, stations);',
    caseIds: ['controller.send.reduced'],
  },
  {
    id: 'controller.no-boost',
    file: CONTROLLER,
    find: 'deps.setBoostHeld(worldCommand.held);',
    replace: '',
    caseIds: ['controller.boost'],
  },
  {
    id: 'controller.reset-keeps-flight',
    file: CONTROLLER,
    find: '    setPhase(FREE);\n  };',
    replace: '  };',
    caseIds: ['controller.reset', 'controller.take-off.undock'],
  },
  {
    id: 'controller.map-raw',
    file: CONTROLLER,
    find: 'return index === null ? null : stationAt(index);',
    replace: 'return index === null ? null : stationAt(0);',
    caseIds: ['controller.map.pick'],
  },
  {
    id: 'loader.no-array-check',
    file: LOADER,
    find: 'z.instanceof(Int16Array).check(lengthIs(HEIGHTS_LENGTH))',
    replace: 'z.unknown()',
    caseIds: ['loader.message.rejects'],
  },
  {
    id: 'loader.no-length-check',
    file: LOADER,
    find: 'return array.length === length;',
    replace: 'return true;',
    caseIds: ['loader.message.lengths'],
  },
  {
    id: 'loader.no-progress',
    file: LOADER,
    find: "z.object({ type: z.literal('progress'), value: z.number() }),",
    replace: '',
    caseIds: ['loader.message.progress'],
  },
  {
    id: 'loader.no-error',
    file: LOADER,
    find: "z.object({ type: z.literal('error') }),",
    replace: '',
    caseIds: ['loader.message.error'],
  },
  {
    id: 'loader.no-minimap',
    file: LOADER,
    find: 'minimap: z.instanceof(Uint8ClampedArray),',
    replace: 'minimap: z.instanceof(Uint8Array),',
    caseIds: ['loader.message.done'],
  },
  {
    id: 'pixel.no-flip',
    file: PIXEL,
    find: '(size - 1 - row) * rowLength',
    replace: 'row * rowLength',
    caseIds: ['pixel.flip'],
  },
  {
    id: 'pixel.linear-min',
    file: PIXEL,
    find: 'texture.minFilter = NearestMipmapNearestFilter;',
    replace: '',
    caseIds: ['pixel.filters'],
  },
  {
    id: 'terrain.keeps-empty',
    file: TERRAIN,
    find: 'if (chunk.indices.length === 0) {',
    replace: 'if (chunk.indices.length < 0) {',
    caseIds: ['terrain.chunks'],
  },
  {
    id: 'terrain.raw-normals',
    file: TERRAIN,
    find: 'new BufferAttribute(chunk.normals, 3, true)',
    replace: 'new BufferAttribute(chunk.normals, 3)',
    caseIds: ['terrain.chunks'],
  },
  {
    id: 'terrain.leak-material',
    file: TERRAIN,
    find: '    material.dispose();\n',
    replace: '',
    caseIds: ['terrain.dispose'],
  },
  {
    id: 'start-error.reason-lost',
    file: 'src/scene/runtime/world-start-error.ts',
    find: 'return error instanceof WorldStartError ? error.reason : ',
    replace: 'return ',
    caseIds: ['start-error.reason'],
  },
  {
    id: 'renderer.antialias-always',
    file: 'src/scene/runtime/renderer.ts',
    find: "antialias: profile === 'desktop',",
    replace: 'antialias: true,',
    caseIds: ['renderer.attributes'],
  },
  {
    id: 'loop.reschedules-always',
    file: LOOP,
    find: 'if (looping && pending === null) {',
    replace: 'if (looping) {',
    caseIds: ['loop.single-callback', 'loop.restart-in-frame'],
  },
  {
    id: 'loop.start-when-looping',
    file: LOOP,
    find: '    if (looping) {\n      return;\n    }\n\n    looping = true;',
    replace: '    looping = true;',
    caseIds: ['loop.single-callback'],
  },
  {
    id: 'loop.stop-keeps-pending',
    file: LOOP,
    find: '      cancel(pending);\n',
    replace: '',
    caseIds: ['loop.stops'],
  },
];
