import type { WorldCaseId } from '@tests/back/scene/world/world.cases';

export type WorldMutation = Readonly<{
  reason?: string;
  id: string;
  file: string;
  find: string;
  replace: string;
  nth?: number;
  caseIds: readonly WorldCaseId[];
}>;

const CONSTANTS = 'src/scene/world/world.constants.ts';
const HEIGHTMAP_MATH = 'src/scene/world/heightmap-math.ts';
const HEIGHTMAP = 'src/scene/world/heightmap.ts';
const BLOCKS = 'src/scene/world/blocks.ts';
const MESHER = 'src/scene/world/mesher.ts';
const TREES = 'src/scene/world/trees.ts';
const STRUCTURES = 'src/scene/world/structures.ts';
const PALETTE = 'src/scene/world/palette.ts';
const SCATTER = 'src/scene/world/scatter.ts';
const LETTERS = 'src/scene/world/letters.ts';
const MINIMAP = 'src/scene/world/minimap-image.ts';
const TEXTURE = 'src/scene/world/pixel-texture.ts';
const GENERATE = 'src/scene/world/generate-world.ts';
const SCHEMA = 'src/scene/world/world.schema.ts';
const RNG = 'src/scene/world/rng.ts';

export const WORLD_MUTATIONS: readonly WorldMutation[] = [
  {
    id: 'seed.primary',
    file: CONSTANTS,
    find: 'primary: 1907',
    replace: 'primary: 1908',
    caseIds: ['world.noise.stream-values', 'world.height.checksum'],
  },
  {
    id: 'seed.ridge',
    file: CONSTANTS,
    find: 'ridge: 4411',
    replace: 'ridge: 4412',
    caseIds: ['world.noise.stream-values', 'world.height.checksum'],
  },
  {
    id: 'seed.stars',
    file: CONSTANTS,
    find: 'stars: 7093',
    replace: 'stars: 7094',
    caseIds: ['world.scatter.stars'],
  },
  {
    id: 'seed.burst',
    file: CONSTANTS,
    find: 'burst: 7095',
    replace: 'burst: 7096',
    caseIds: ['world.scatter.burst'],
  },
  {
    id: 'seed.fireflies',
    file: CONSTANTS,
    find: 'fireflies: 7094',
    replace: 'fireflies: 7095',
    caseIds: ['world.scatter.fireflies'],
  },
  {
    id: 'seed.letters',
    file: CONSTANTS,
    find: 'letters: 7096',
    replace: 'letters: 7097',
    caseIds: ['world.letters.cells'],
  },
  {
    id: 'seed.texture',
    file: CONSTANTS,
    find: 'texture: 7092',
    replace: 'texture: 7093',
    caseIds: ['world.texture.pixels'],
  },
  {
    id: 'seed.trees',
    file: CONSTANTS,
    find: 'trees: 7091',
    replace: 'trees: 7092',
    caseIds: ['world.trees.count'],
  },
  {
    id: 'rng.nondeterministic',
    file: RNG,
    find: 'let state = seed | 0;',
    replace: 'let state = (seed | 0) + Math.floor(Math.random() * 1000);',
    caseIds: ['world.gen.deterministic'],
  },
  {
    id: 'flatten.inner',
    file: CONSTANTS,
    find: 'FLATTEN_INNER = 5.5',
    replace: 'FLATTEN_INNER = 3',
    caseIds: ['world.station.flat-core', 'world.height.checksum'],
  },
  {
    id: 'flatten.outer',
    file: CONSTANTS,
    find: 'FLATTEN_OUTER = 11',
    replace: 'FLATTEN_OUTER = 12',
    caseIds: ['world.height.checksum'],
  },
  {
    id: 'plate.radius',
    file: CONSTANTS,
    find: 'PLATE_RADIUS = 4.2',
    replace: 'PLATE_RADIUS = 4.6',
    caseIds: ['world.station.plate', 'world.blocks.classes'],
  },
  {
    id: 'station.base-max',
    file: CONSTANTS,
    find: 'STATION_BASE_MAX = 24',
    replace: 'STATION_BASE_MAX = 20',
    caseIds: ['world.station.bases'],
  },
  {
    id: 'station.base-min',
    file: CONSTANTS,
    find: 'STATION_BASE_MIN = SEA_LEVEL + 2',
    replace: 'STATION_BASE_MIN = SEA_LEVEL + 3',
    caseIds: ['world.station.bases'],
  },
  {
    id: 'height.floor-not-round',
    file: HEIGHTMAP,
    find: 'Math.max(1, Math.round(height))',
    replace: 'Math.max(1, Math.floor(height))',
    caseIds: ['world.height.checksum'],
  },
  {
    id: 'height.outside-zero',
    file: HEIGHTMAP,
    find: 'return 1;',
    replace: 'return 0;',
    caseIds: ['world.height.lookup'],
  },
  {
    id: 'height.mountain-scale',
    file: HEIGHTMAP_MATH,
    find: '* 46 *',
    replace: '* 45 *',
    caseIds: ['world.height.checksum', 'world.noise.stream-values'],
  },
  {
    id: 'height.edge-falloff',
    file: HEIGHTMAP_MATH,
    find: 'smooth(0.8, 1, edge)',
    replace: 'smooth(0.85, 1, edge)',
    caseIds: ['world.height.checksum', 'world.noise.stream-values'],
  },
  {
    id: 'blocks.depth-shade',
    file: CONSTANTS,
    find: 'DEPTH_SHADE = 0.1',
    replace: 'DEPTH_SHADE = 0.2',
    caseIds: ['world.blocks.depth-shade', 'world.blocks.classes'],
  },
  {
    id: 'blocks.depth-cap',
    file: CONSTANTS,
    find: 'DEPTH_SHADE_MAX_DEPTH = 4',
    replace: 'DEPTH_SHADE_MAX_DEPTH = 5',
    caseIds: ['world.blocks.depth-shade', 'world.blocks.classes'],
  },
  {
    id: 'blocks.sand-max',
    file: CONSTANTS,
    find: 'SAND_MAX = SEA_LEVEL + 1',
    replace: 'SAND_MAX = SEA_LEVEL + 2',
    caseIds: ['world.blocks.classes'],
  },
  {
    id: 'blocks.stone-from',
    file: CONSTANTS,
    find: 'STONE_FROM = 22',
    replace: 'STONE_FROM = 23',
    caseIds: ['world.blocks.classes'],
  },
  {
    id: 'blocks.snow-from',
    file: CONSTANTS,
    find: 'SNOW_FROM = 30',
    replace: 'SNOW_FROM = 31',
    caseIds: ['world.blocks.classes'],
  },
  {
    id: 'blocks.plate-kind',
    file: BLOCKS,
    find: 'if (plate && depth === 0) {',
    replace: 'if (plate && depth >= 0) {',
    caseIds: ['world.blocks.classes', 'world.station.plate'],
  },
  {
    id: 'palette.grass',
    file: PALETTE,
    find: "grass: linearFromHex('#58a043')",
    replace: "grass: linearFromHex('#58a044')",
    caseIds: ['world.blocks.linear-colors', 'world.blocks.classes'],
  },
  {
    id: 'trees.chance',
    file: CONSTANTS,
    find: 'TREE_CHANCE = 0.022',
    replace: 'TREE_CHANCE = 0.03',
    caseIds: ['world.trees.count'],
  },
  {
    id: 'trees.clearance',
    file: CONSTANTS,
    find: 'TREE_STATION_CLEARANCE = 9',
    replace: 'TREE_STATION_CLEARANCE = 7',
    caseIds: ['world.trees.count', 'world.trees.rules'],
  },
  {
    id: 'trees.top-max',
    file: CONSTANTS,
    find: 'TREE_TOP_MAX = 21',
    replace: 'TREE_TOP_MAX = 25',
    caseIds: ['world.trees.count', 'world.trees.rules'],
  },
  {
    id: 'trees.top-min',
    file: CONSTANTS,
    find: 'TREE_TOP_MIN = SEA_LEVEL + 2',
    replace: 'TREE_TOP_MIN = SEA_LEVEL',
    caseIds: ['world.trees.count', 'world.trees.rules'],
  },
  {
    id: 'trees.height-min',
    file: CONSTANTS,
    find: 'TREE_HEIGHT_MIN = 3',
    replace: 'TREE_HEIGHT_MIN = 4',
    caseIds: ['world.trees.rules', 'world.trees.count'],
  },
  {
    id: 'trees.leaf-radius',
    file: CONSTANTS,
    find: 'TREE_LEAF_RADIUS = 3',
    replace: 'TREE_LEAF_RADIUS = 4',
    caseIds: ['world.trees.cells'],
  },
  {
    id: 'trees.lantern-chance',
    file: CONSTANTS,
    find: 'TREE_LANTERN_CHANCE = 0.25',
    replace: 'TREE_LANTERN_CHANCE = 0.3',
    caseIds: ['world.trees.count'],
  },
  {
    id: 'trees.trunk-overwrite',
    file: TREES,
    find: 'setCellIfEmpty(occupancy, ix + dx',
    replace: 'setCell(occupancy, ix + dx',
    caseIds: ['world.trees.count'],
  },
  {
    id: 'mesher.neighbour-offset',
    file: MESHER,
    find: 'neighbour: [1, 0, 0],',
    replace: 'neighbour: [2, 0, 0],',
    caseIds: ['world.mesh.stair', 'world.mesh.naive-count'],
  },
  {
    id: 'mesher.ground-solid',
    file: MESHER,
    find: 'if (y < 1) {',
    replace: 'if (y < 0) {',
    caseIds: ['world.mesh.single-block', 'world.mesh.naive-count'],
  },
  {
    id: 'mesher.wrap-z-low',
    file: MESHER,
    find: 'iz < 0 || iz >= MAP_SIZE',
    replace: 'iz >= MAP_SIZE',
    caseIds: ['world.mesh.map-edge'],
  },
  {
    id: 'mesher.wrap-z-high',
    file: MESHER,
    find: 'iz < 0 || iz >= MAP_SIZE',
    replace: 'iz < 0',
    caseIds: ['world.mesh.map-edge'],
  },
  {
    id: 'mesher.chunk-border-double',
    file: MESHER,
    find: 'if (isSolid(cells, ix + nx, y + ny, iz + nz)) {',
    replace:
      'if (isSolid(cells, ix + nx, y + ny, iz + nz) && Math.floor((ix + nx) / CHUNK_SIZE) === chunkX) {',
    caseIds: ['world.mesh.chunk-border', 'world.mesh.naive-count'],
  },
  {
    id: 'mesher.chunk-border-missing',
    file: MESHER,
    find: 'ix < (chunkX + 1) * CHUNK_SIZE;',
    replace: 'ix < (chunkX + 1) * CHUNK_SIZE - 1;',
    caseIds: ['world.mesh.chunk-border', 'world.mesh.naive-count'],
  },
  {
    id: 'mesher.chunk-size',
    file: CONSTANTS,
    find: 'CHUNK_SIZE = 32',
    replace: 'CHUNK_SIZE = 16',
    caseIds: ['world.mesh.chunk-limits'],
  },
  {
    id: 'mesher.top-winding',
    file: MESHER,
    find: '[0, 1, 0],\n      [0, 1, 1],\n      [1, 1, 1],\n      [1, 1, 0],',
    replace: '[1, 1, 0],\n      [1, 1, 1],\n      [0, 1, 1],\n      [0, 1, 0],',
    caseIds: ['world.mesh.geometry'],
  },
  {
    id: 'mesher.cell-y',
    file: MESHER,
    find: 'y - 1 + (offsets[1] ?? 0)',
    replace: 'y + (offsets[1] ?? 0)',
    caseIds: ['world.mesh.cell-position'],
  },
  {
    id: 'mesher.cell-x',
    file: MESHER,
    find: 'ix - MAP_HALF + (offsets[0] ?? 0)',
    replace: 'ix - MAP_HALF + 0.5 + (offsets[0] ?? 0)',
    caseIds: ['world.mesh.cell-position', 'world.mesh.geometry'],
  },
  {
    id: 'mesher.top-uses-side',
    file: MESHER,
    find: 'useTopColor: true,',
    replace: 'useTopColor: false,',
    caseIds: ['world.mesh.face-colors'],
  },
  {
    id: 'shade.bottom',
    file: CONSTANTS,
    find: 'bottom: 0.55',
    replace: 'bottom: 0.5',
    caseIds: ['world.mesh.face-colors'],
  },
  {
    id: 'shade.x',
    file: CONSTANTS,
    find: 'x: 0.86',
    replace: 'x: 0.9',
    caseIds: ['world.mesh.face-colors'],
  },
  {
    id: 'shade.z',
    file: CONSTANTS,
    find: 'z: 1 }',
    replace: 'z: 0.95 }',
    caseIds: ['world.mesh.face-colors'],
  },
  {
    id: 'shade.top',
    file: CONSTANTS,
    find: 'top: 1,',
    replace: 'top: 0.9,',
    caseIds: ['world.mesh.face-colors'],
  },
  {
    id: 'struct.post-height',
    file: STRUCTURES,
    find: 'POST_HEIGHT = 3',
    replace: 'POST_HEIGHT = 4',
    caseIds: ['world.struct.posts'],
  },
  {
    id: 'struct.pillar-height',
    file: STRUCTURES,
    find: 'PILLAR_HEIGHT = 7',
    replace: 'PILLAR_HEIGHT = 8',
    caseIds: ['world.struct.systems'],
  },
  {
    id: 'struct.antenna-height',
    file: STRUCTURES,
    find: 'ANTENNA_HEIGHT = 16',
    replace: 'ANTENNA_HEIGHT = 15',
    caseIds: ['world.struct.antenna'],
  },
  {
    id: 'struct.antenna-band',
    file: STRUCTURES,
    find: 'ANTENNA_BAND_AT = 3',
    replace: 'ANTENNA_BAND_AT = 2',
    caseIds: ['world.struct.antenna'],
  },
  {
    id: 'struct.mast-offset',
    file: CONSTANTS,
    find: 'MAST_OFFSET = [2.5, 17.5, -1.5]',
    replace: 'MAST_OFFSET = [2.5, 18.5, -1.5]',
    caseIds: ['world.struct.antenna'],
  },
  {
    id: 'struct.ai-up',
    file: CONSTANTS,
    find: 'AI_NODE_UP = 7',
    replace: 'AI_NODE_UP = 8',
    caseIds: ['world.struct.ai-nodes'],
  },
  {
    id: 'struct.ai-offsets',
    file: CONSTANTS,
    find: '[-6, -2, 2, 6]',
    replace: '[-6, -2, 2, 7]',
    caseIds: ['world.struct.ai-nodes'],
  },
  {
    id: 'struct.ai-dz',
    file: CONSTANTS,
    find: 'AI_NODE_DZ = -3',
    replace: 'AI_NODE_DZ = -2',
    caseIds: ['world.struct.ai-nodes'],
  },
  {
    id: 'struct.post-glow-colour',
    file: PALETTE,
    find: 'post: [2.2, 1.55, 0.6]',
    replace: 'post: [2.3, 1.55, 0.6]',
    caseIds: ['world.struct.posts'],
  },
  {
    id: 'struct.sculpture-block',
    file: STRUCTURES,
    find: '[-1, 6, 1],\n];\n\nconst SCULPTURE_GLOWS',
    replace: '[-1, 6, 2],\n];\n\nconst SCULPTURE_GLOWS',
    caseIds: ['world.struct.this-world'],
  },
  {
    id: 'struct.sculpture-glow',
    file: STRUCTURES,
    find: '[-1, 4, 0],\n];',
    replace: '[-1, 4, 1],\n];',
    caseIds: ['world.struct.this-world'],
  },
  {
    id: 'struct.glow-scale',
    file: STRUCTURES,
    find: 'GLOW_COLORS.post, 0.55',
    replace: 'GLOW_COLORS.post, 0.5',
    caseIds: ['world.struct.glow-total', 'world.struct.posts'],
  },
  {
    id: 'scatter.star-radius',
    file: CONSTANTS,
    find: 'STAR_RADIUS = 520',
    replace: 'STAR_RADIUS = 500',
    caseIds: ['world.scatter.stars'],
  },
  {
    id: 'scatter.cloud-threshold',
    file: CONSTANTS,
    find: 'CLOUD_THRESHOLD = 0.38',
    replace: 'CLOUD_THRESHOLD = 0.4',
    caseIds: ['world.scatter.clouds'],
  },
  {
    id: 'scatter.cloud-base',
    file: CONSTANTS,
    find: 'CLOUD_BASE_Y = 46',
    replace: 'CLOUD_BASE_Y = 45',
    caseIds: ['world.scatter.clouds'],
  },
  {
    id: 'scatter.cloud-step',
    file: CONSTANTS,
    find: 'CLOUD_STEP = 4',
    replace: 'CLOUD_STEP = 5',
    caseIds: ['world.scatter.clouds'],
  },
  {
    id: 'scatter.burst-up',
    file: SCATTER,
    find: 'const up = 0.4 + random() * 1.4;',
    replace: 'const up = 0.5 + random() * 1.4;',
    caseIds: ['world.scatter.burst'],
  },
  {
    id: 'scatter.firefly-margin',
    file: SCATTER,
    find: 'FIREFLY_MARGIN = 6',
    replace: 'FIREFLY_MARGIN = 5',
    caseIds: ['world.scatter.fireflies'],
  },
  {
    id: 'scatter.firefly-lift',
    file: SCATTER,
    find: 'FIREFLY_LIFT = 4',
    replace: 'FIREFLY_LIFT = 5',
    caseIds: ['world.scatter.fireflies'],
  },
  {
    id: 'scatter.firefly-count',
    file: CONSTANTS,
    find: 'FIREFLY_COUNT = 520',
    replace: 'FIREFLY_COUNT = 500',
    caseIds: ['world.scatter.fireflies'],
  },
  {
    id: 'scatter.star-count',
    file: CONSTANTS,
    find: 'STAR_COUNT = 1600',
    replace: 'STAR_COUNT = 1500',
    caseIds: ['world.scatter.stars'],
  },
  {
    id: 'letters.scale',
    file: CONSTANTS,
    find: 'LETTER_SCALE = 0.72',
    replace: 'LETTER_SCALE = 0.8',
    caseIds: ['world.letters.cells'],
  },
  {
    id: 'letters.advance',
    file: CONSTANTS,
    find: 'LETTER_ADVANCE = 6',
    replace: 'LETTER_ADVANCE = 7',
    caseIds: ['world.letters.cells'],
  },
  {
    id: 'letters.line-gap',
    file: CONSTANTS,
    find: 'LETTER_LINE_GAP = 9',
    replace: 'LETTER_LINE_GAP = 10',
    caseIds: ['world.letters.cells'],
  },
  {
    id: 'letters.glyph-bit',
    file: CONSTANTS,
    find: "V: ['10001', '10001', '10001', '10001', '10001', '01010', '00100']",
    replace: "V: ['10001', '10001', '10001', '10001', '10001', '01010', '01100']",
    caseIds: ['world.letters.cells'],
  },
  {
    id: 'letters.delay-spread',
    file: LETTERS,
    find: 'DELAY_SPREAD = 0.55',
    replace: 'DELAY_SPREAD = 0.6',
    caseIds: ['world.letters.cells'],
  },
  {
    id: 'letters.glyph-set',
    file: SCHEMA,
    find: "Object.keys(GLYPHS).join('')",
    replace: "Object.keys(GLYPHS).join('') + 'X'",
    caseIds: ['world.letters.unknown-glyph'],
  },
  {
    id: 'minimap.grass-max',
    file: CONSTANTS,
    find: 'MINIMAP_GRASS_MAX = 20',
    replace: 'MINIMAP_GRASS_MAX = 21',
    caseIds: ['world.minimap.bands'],
  },
  {
    id: 'minimap.stone-max',
    file: CONSTANTS,
    find: 'MINIMAP_STONE_MAX = 28',
    replace: 'MINIMAP_STONE_MAX = 29',
    caseIds: ['world.minimap.bands'],
  },
  {
    id: 'minimap.shade-base',
    file: CONSTANTS,
    find: 'MINIMAP_SHADE_BASE = 0.7',
    replace: 'MINIMAP_SHADE_BASE = 0.6',
    caseIds: ['world.minimap.bands'],
  },
  {
    id: 'minimap.sand-colour',
    file: PALETTE,
    find: 'sand: [200, 184, 130]',
    replace: 'sand: [200, 184, 131]',
    caseIds: ['world.minimap.bands'],
  },
  {
    id: 'minimap.transpose',
    file: MINIMAP,
    find: 'const offset = (row * MAP_SIZE + column) * 4;',
    replace: 'const offset = (column * MAP_SIZE + row) * 4;',
    caseIds: ['world.minimap.bands'],
  },
  {
    id: 'texture.edge',
    file: TEXTURE,
    find: 'EDGE_KEEP = 0.78',
    replace: 'EDGE_KEEP = 0.8',
    caseIds: ['world.texture.pixels'],
  },
  {
    id: 'texture.speckle',
    file: TEXTURE,
    find: 'SPECKLE_CHANCE = 0.12',
    replace: 'SPECKLE_CHANCE = 0.2',
    caseIds: ['world.texture.pixels'],
  },
  {
    id: 'texture.base',
    file: TEXTURE,
    find: 'BASE_LEVEL = 200',
    replace: 'BASE_LEVEL = 201',
    caseIds: ['world.texture.pixels'],
  },
  {
    id: 'progress.heights',
    file: CONSTANTS,
    find: 'heights: 0.4,',
    replace: 'heights: 0.5,',
    caseIds: ['world.gen.progress'],
  },
  {
    id: 'progress.chunks',
    file: CONSTANTS,
    find: 'chunks: 0.95,',
    replace: 'chunks: 0.9,',
    caseIds: ['world.gen.progress'],
  },
  {
    id: 'transfer.minimap-missing',
    file: GENERATE,
    find: '    data.minimap,\n',
    replace: '',
    caseIds: ['world.gen.transferables'],
  },
  {
    id: 'transfer.chunks-missing',
    file: GENERATE,
    find: 'chunk.positions, chunk.normals, chunk.uvs, chunk.colors, chunk.indices',
    replace: 'chunk.positions, chunk.normals, chunk.uvs, chunk.colors',
    caseIds: ['world.gen.transferables'],
  },
  {
    id: 'schema.min-lines',
    file: SCHEMA,
    find: 'z.minLength(1)',
    replace: 'z.minLength(0)',
    caseIds: ['world.request.schema'],
  },
  {
    id: 'schema.max-lines',
    file: SCHEMA,
    find: 'z.maxLength(3)',
    replace: 'z.maxLength(4)',
    caseIds: ['world.request.schema'],
  },
];

export const EQUIVALENT_WORLD_MUTATIONS: readonly WorldMutation[] = [
  {
    id: 'palette.gamma-linear-segment',
    file: PALETTE,
    find: '0.0773993808',
    replace: '0.08',
    caseIds: [],
    reason: 'the linear segment applies below sRGB 0.04045 and no palette channel is that dark',
  },
];
