import type { MotionCaseId } from '@tests/back/motion/motion.cases';

export type MotionMutation = Readonly<{
  id: string;
  file: string;
  find: string;
  replace: string;
  nth?: number;
  caseIds: readonly MotionCaseId[];
}>;

const TOKENS = 'src/motion/motion.tokens.ts';
const PANEL = 'src/motion/panel-entrance.ts';
const TITLE_CARD = 'src/motion/title-card.ts';
const REDUCED = 'src/motion/reduced-motion.ts';
const MAGNET = 'src/motion/magnet.ts';
const ROLL = 'src/motion/number-roll.ts';
const STEPS = 'src/motion/timeline-steps.ts';

export const MOTION_MUTATIONS: readonly MotionMutation[] = [
  {
    id: 'tokens.wipe-in-duration',
    file: TOKENS,
    find: "wipeIn: { duration: 0.28, ease: 'power4.in'",
    replace: "wipeIn: { duration: 0.3, ease: 'power4.in'",
    caseIds: ['motion.panel.wipe-in'],
  },
  {
    id: 'tokens.wipe-out-position',
    file: TOKENS,
    find: "wipeOut: { duration: 0.45, ease: 'expo.out', stagger: 0, position: 0.28 }",
    replace: "wipeOut: { duration: 0.45, ease: 'expo.out', stagger: 0, position: 0.3 }",
    caseIds: ['motion.panel.wipe-out'],
  },
  {
    id: 'tokens.tag-ease',
    file: TOKENS,
    find: "tag: { duration: 0.4, ease: 'expo.out'",
    replace: "tag: { duration: 0.4, ease: 'power3.out'",
    caseIds: ['motion.panel.tag'],
  },
  {
    id: 'tokens.title-stagger',
    file: TOKENS,
    find: 'stagger: 0.018',
    replace: 'stagger: 0.02',
    caseIds: ['motion.panel.title-chars'],
  },
  {
    id: 'tokens.lede-position',
    file: TOKENS,
    find: "lede: { duration: 0.5, ease: 'power3.out', stagger: 0.08, position: 0.5 }",
    replace: "lede: { duration: 0.5, ease: 'power3.out', stagger: 0.08, position: 0.55 }",
    caseIds: ['motion.panel.lede'],
  },
  {
    id: 'tokens.items-duration',
    file: TOKENS,
    find: 'items: { duration: 0.45',
    replace: 'items: { duration: 0.5',
    caseIds: ['motion.panel.items'],
  },
  {
    id: 'tokens.stats-ease',
    file: TOKENS,
    find: "stats: { duration: 0.5, ease: 'back.out(1.8)'",
    replace: "stats: { duration: 0.5, ease: 'back.out(2.6)'",
    caseIds: ['motion.panel.stats'],
  },
  {
    id: 'tokens.chips-stagger',
    file: TOKENS,
    find: 'stagger: 0.022',
    replace: 'stagger: 0.02',
    caseIds: ['motion.panel.chips'],
  },
  {
    id: 'tokens.result-position',
    file: TOKENS,
    find: 'position: 0.85',
    replace: 'position: 0.8',
    caseIds: ['motion.panel.result'],
  },
  {
    id: 'tokens.roll-duration',
    file: TOKENS,
    find: 'numberRoll: { duration: 0.9',
    replace: 'numberRoll: { duration: 1',
    caseIds: ['motion.panel.number-roll'],
  },
  {
    id: 'tokens.title-card-chars-in',
    file: TOKENS,
    find: 'charsIn: { duration: 0.65',
    replace: 'charsIn: { duration: 0.7',
    caseIds: ['motion.title-card.chars-in'],
  },
  {
    id: 'tokens.title-card-chars-out',
    file: TOKENS,
    find: 'position: 1.35',
    replace: 'position: 1.3',
    caseIds: ['motion.title-card.chars-out'],
  },
  {
    id: 'tokens.title-card-line-in',
    file: TOKENS,
    find: "lineIn: { duration: 0.5, ease: 'expo.out'",
    replace: "lineIn: { duration: 0.5, ease: 'power3.out'",
    caseIds: ['motion.title-card.line-in'],
  },
  {
    id: 'tokens.title-card-kicker-in',
    file: TOKENS,
    find: 'position: 0.08',
    replace: 'position: 0.1',
    caseIds: ['motion.title-card.kicker-in'],
  },
  {
    id: 'tokens.title-card-line-out',
    file: TOKENS,
    find: "lineOut: { duration: 0.4, ease: 'power3.in'",
    replace: "lineOut: { duration: 0.45, ease: 'power3.in'",
    caseIds: ['motion.title-card.line-out'],
  },
  {
    id: 'tokens.title-card-kicker-out-ease',
    file: TOKENS,
    find: "ease: 'power1.out'",
    replace: "ease: 'power3.out'",
    caseIds: ['motion.title-card.kicker-out'],
  },
  {
    id: 'tokens.magnet-factor',
    file: TOKENS,
    find: 'factorY: 0.4',
    replace: 'factorY: 0.3',
    caseIds: ['motion.magnet.tokens', 'motion.magnet.offset'],
  },
  {
    id: 'tokens.intro',
    file: TOKENS,
    find: 'introMs: 3200',
    replace: 'introMs: 3000',
    caseIds: ['motion.scene.intro'],
  },
  {
    id: 'tokens.auto-dock',
    file: TOKENS,
    find: 'autoDockMs: 2600',
    replace: 'autoDockMs: 3000',
    caseIds: ['motion.scene.auto-dock'],
  },
  {
    id: 'tokens.ring',
    file: TOKENS,
    find: 'ringSeconds: 1.3',
    replace: 'ringSeconds: 1.4',
    caseIds: ['motion.scene.ring'],
  },
  {
    id: 'tokens.burst',
    file: TOKENS,
    find: 'burstSeconds: 1.4',
    replace: 'burstSeconds: 1.3',
    caseIds: ['motion.scene.burst'],
  },
  {
    id: 'tokens.flash-take-off',
    file: TOKENS,
    find: 'flashTakeOff: { opacity: 0.6, ms: 900 }',
    replace: 'flashTakeOff: { opacity: 0.85, ms: 520 }',
    caseIds: ['motion.scene.flash-take-off'],
  },
  {
    id: 'tokens.flash-send',
    file: TOKENS,
    find: 'flashSend: { opacity: 0.5, ms: 700 }',
    replace: 'flashSend: { opacity: 0.5, ms: 900 }',
    caseIds: ['motion.scene.flash-send'],
  },
  {
    id: 'tokens.css-panel-in',
    file: TOKENS,
    find: 'panelTransformIn: 520',
    replace: 'panelTransformIn: 420',
    caseIds: ['motion.css.transitions'],
  },
  {
    id: 'panel.wipe-origin-set',
    file: PANEL,
    find: "to: { transformOrigin: 'right' }",
    replace: "to: { transformOrigin: 'left' }",
    caseIds: ['motion.panel.wipe-out', 'motion.panel.from-states'],
  },
  {
    id: 'panel.tag-offset',
    file: PANEL,
    find: 'from: { x: -24, opacity: 0 }',
    replace: 'from: { x: -18, opacity: 0 }',
    caseIds: ['motion.panel.from-states'],
  },
  {
    id: 'panel.lede-layout-property',
    file: PANEL,
    find: 'from: { y: 14, opacity: 0 }',
    replace: 'from: { top: 14, opacity: 0 }',
    caseIds: ['motion.panel.from-states', 'motion.panel.transform-opacity-only'],
  },
  {
    id: 'panel.chips-token-swapped',
    file: PANEL,
    find: 'tween: PANEL_MOTION.chips',
    replace: 'tween: PANEL_MOTION.stats',
    caseIds: ['motion.panel.chips'],
  },
  {
    id: 'panel.item-selector',
    file: PANEL,
    find: `item: '[data-motion="item"]'`,
    replace: `item: '[data-motion="items"]'`,
    caseIds: ['motion.panel.selectors'],
  },
  {
    id: 'panel.stat-value-selector',
    file: PANEL,
    find: `statValue: '[data-motion="stat-value"]'`,
    replace: `statValue: '[data-motion="stat"] b'`,
    caseIds: ['motion.panel.selectors'],
  },
  {
    id: 'title-card.line-out-origin',
    file: TITLE_CARD,
    find: "to: { scaleX: 0, transformOrigin: 'left' }",
    replace: "to: { scaleX: 0, transformOrigin: 'right' }",
    caseIds: ['motion.title-card.line-out'],
  },
  {
    id: 'title-card.card-hidden-step',
    file: TITLE_CARD,
    find: "{ kind: 'set', target: 'card', to: { opacity: 1 }, position: 0 }",
    replace: "{ kind: 'set', target: 'card', to: { opacity: 0 }, position: 0 }",
    caseIds: ['motion.title-card.card-shown'],
  },
  {
    id: 'title-card.chars-in-skew',
    file: TITLE_CARD,
    find: 'from: { yPercent: 120, skewX: -18 }',
    replace: 'from: { yPercent: 115, skewX: -18 }',
    caseIds: ['motion.title-card.chars-in'],
  },
  {
    id: 'title-card.chars-out-distance',
    file: TITLE_CARD,
    find: 'to: { yPercent: -120 }',
    replace: 'to: { yPercent: -100 }',
    caseIds: ['motion.title-card.chars-out'],
  },
  {
    id: 'title-card.kicker-in-rise',
    file: TITLE_CARD,
    find: 'from: { y: 20, opacity: 0 }',
    replace: 'from: { y: 14, opacity: 0 }',
    caseIds: ['motion.title-card.kicker-in'],
  },
  {
    id: 'title-card.kicker-out-dropped',
    file: TITLE_CARD,
    find: "  { kind: 'to', target: 'tag', to: { opacity: 0 }, tween: TITLE_CARD_MOTION.kickerOut },\n",
    replace: '',
    caseIds: ['motion.title-card.kicker-out'],
  },
  {
    id: 'reduced.query-inverted',
    file: REDUCED,
    find: "MOTION_ALLOWED_QUERY = '(prefers-reduced-motion: no-preference)'",
    replace: "MOTION_ALLOWED_QUERY = '(prefers-reduced-motion: reduce)'",
    caseIds: [
      'motion.reduced.query',
      'motion.reduced.reduce',
      'motion.reduced.no-preference',
      'motion.magnet.enabled',
      'motion.magnet.disabled.reduced',
      'motion.magnet.disabled.coarse',
    ],
  },
  {
    id: 'reduced.ignored',
    file: REDUCED,
    find: 'return !matchesMedia(MOTION_ALLOWED_QUERY);',
    replace: 'return false;',
    caseIds: [
      'motion.reduced.reduce',
      'motion.reduced.no-window',
      'motion.magnet.disabled.reduced',
    ],
  },
  {
    id: 'reduced.server-allows-motion',
    file: REDUCED,
    find: "typeof window.matchMedia !== 'function') {\n    return false;",
    replace: "typeof window.matchMedia !== 'function') {\n    return true;",
    caseIds: ['motion.reduced.no-window'],
  },
  {
    id: 'magnet.reduced-ignored',
    file: MAGNET,
    find: 'return !prefersReducedMotion() && matchesMedia(FINE_POINTER_QUERY);',
    replace: 'return matchesMedia(FINE_POINTER_QUERY);',
    caseIds: ['motion.magnet.disabled.reduced'],
  },
  {
    id: 'magnet.pointer-ignored',
    file: MAGNET,
    find: 'return !prefersReducedMotion() && matchesMedia(FINE_POINTER_QUERY);',
    replace: 'return !prefersReducedMotion();',
    caseIds: ['motion.magnet.disabled.coarse'],
  },
  {
    id: 'magnet.centre-shift',
    file: MAGNET,
    find: 'rect.height / 2',
    replace: 'rect.height / 3',
    caseIds: ['motion.magnet.offset'],
  },
  {
    id: 'roll.no-stagger',
    file: ROLL,
    find: 'tween.position + tween.stagger * index',
    replace: 'tween.position',
    caseIds: ['motion.panel.number-roll'],
  },
  {
    id: 'roll.single-digit',
    file: ROLL,
    find: String.raw`/^(\D*)(\d+)(.*)$/`,
    replace: String.raw`/^(\D*)(\d)(.*)$/`,
    caseIds: ['motion.roll.parse.prefix-suffix', 'motion.roll.mid-value'],
  },
  {
    id: 'roll.prefix-dropped',
    file: ROLL,
    find: 'return `${target.prefix}${Math.round(value)}${target.suffix}`;',
    replace: 'return `${Math.round(value)}${target.suffix}`;',
    caseIds: ['motion.roll.format'],
  },
  {
    id: 'roll.floor',
    file: ROLL,
    find: 'Math.round(value)',
    replace: 'Math.floor(value)',
    caseIds: ['motion.roll.format'],
  },
  {
    id: 'roll.null-not-skipped',
    file: ROLL,
    find: 'if (target === null) {\n      return [];',
    replace: 'if (target === null && holders.length < 0) {\n      return [];',
    caseIds: ['motion.roll.skip-non-numeric'],
  },
  {
    id: 'roll.restore-dropped',
    file: ROLL,
    find: 'holder.textContent = original;',
    replace: 'holder.textContent = holder.textContent;',
    caseIds: [
      'motion.roll.restore.complete',
      'motion.roll.restore.revert',
      'motion.roll.restore.kill',
      'motion.roll.restore.context',
    ],
  },
  {
    id: 'settle.no-complete',
    file: STEPS,
    find: "timeline.eventCallback('onComplete', once);",
    replace: '',
    caseIds: ['motion.roll.restore.complete'],
  },
  {
    id: 'settle.no-interrupt',
    file: STEPS,
    find: "timeline.eventCallback('onInterrupt', once);",
    replace: '',
    caseIds: ['motion.roll.restore.revert', 'motion.roll.restore.kill'],
  },
  {
    id: 'settle.no-context',
    file: STEPS,
    find: '  gsap.context(() => {\n    return once;\n  });\n',
    replace: '',
    caseIds: ['motion.roll.restore.context'],
  },
  {
    id: 'settle.repeats',
    file: STEPS,
    find: 'settled = true;',
    replace: 'settled = false;',
    caseIds: ['motion.roll.settle-once'],
  },
];
