import type { EnvironmentCaseId } from '@tests/back/scene/visuals/environment.cases';

export type EnvironmentMutation = Readonly<{
  id: string;
  file: string;
  find: string;
  replace: string;
  nth?: number;
  caseIds: readonly EnvironmentCaseId[];
}>;

const DIR = 'src/scene/visuals/environment';
const MATH = `${DIR}/environment-math.ts`;
const CONSTANTS = `${DIR}/environment.constants.ts`;
const GLOW = `${DIR}/glow-module.ts`;
const WATER = `${DIR}/water-module.ts`;
const SKY = `${DIR}/sky-module.ts`;
const MOON = `${DIR}/moon-module.ts`;
const STARS = `${DIR}/stars-module.ts`;
const CLOUDS = `${DIR}/clouds-module.ts`;
const FIREFLIES = `${DIR}/fireflies-module.ts`;
const LIGHTS = `${DIR}/lights-module.ts`;
const ENV = `${DIR}/environment.ts`;

export const ENVIRONMENT_MUTATIONS: readonly EnvironmentMutation[] = [
  {
    id: 'cloud.speed',
    file: CONSTANTS,
    find: 'CLOUD_DRIFT_SPEED = 0.8',
    replace: 'CLOUD_DRIFT_SPEED = 0.9',
    caseIds: ['math.cloud.middle', 'math.cloud.wrap', 'clouds.drift'],
  },
  {
    id: 'cloud.span',
    file: CONSTANTS,
    find: 'CLOUD_DRIFT_SPAN = 60',
    replace: 'CLOUD_DRIFT_SPAN = 50',
    caseIds: ['math.cloud.start', 'math.cloud.middle', 'clouds.drift'],
  },
  {
    id: 'cloud.no-centre',
    file: MATH,
    find: ' - CLOUD_DRIFT_SPAN / 2',
    replace: '',
    caseIds: ['math.cloud.start', 'math.cloud.middle', 'clouds.drift'],
  },
  {
    id: 'cloud.no-wrap',
    file: MATH,
    find: ' % CLOUD_DRIFT_SPAN',
    replace: '',
    caseIds: ['math.cloud.wrap', 'clouds.drift'],
  },
  {
    id: 'firefly.narrow-count',
    file: MATH,
    find: "profile === 'narrow' ?",
    replace: "profile === 'desktop' ?",
    caseIds: ['math.firefly.count', 'fireflies.range'],
  },
  {
    id: 'firefly.no-cap',
    file: MATH,
    find: 'Math.min(wanted, available)',
    replace: 'wanted',
    caseIds: ['math.firefly.count'],
  },
  {
    id: 'firefly.time-always',
    file: MATH,
    find: 'return reducedMotion ? 0 : time;',
    replace: 'return time;',
    caseIds: ['math.firefly.time', 'fireflies.uniforms'],
  },
  {
    id: 'firefly.time-inverted',
    file: MATH,
    find: 'return reducedMotion ? 0 : time;',
    replace: 'return reducedMotion ? time : 0;',
    caseIds: ['math.firefly.time', 'fireflies.uniforms'],
  },
  {
    id: 'water.scroll-x',
    file: CONSTANTS,
    find: 'x: 0.05, y: 0.03',
    replace: 'x: 0.03, y: 0.03',
    caseIds: ['math.water.offset', 'water.scroll'],
  },
  {
    id: 'water.scroll-y',
    file: CONSTANTS,
    find: 'x: 0.05, y: 0.03',
    replace: 'x: 0.05, y: 0.05',
    caseIds: ['math.water.offset', 'water.scroll'],
  },
  {
    id: 'water.no-update',
    file: WATER,
    find: 'map.offset.set(waterOffsetX(frame.time), waterOffsetY(frame.time));',
    replace: 'void frame;',
    caseIds: ['water.scroll'],
  },
  {
    id: 'water.shared-texture',
    file: WATER,
    find: 'pixelTexture.clone()',
    replace: 'pixelTexture',
    caseIds: ['water.plane', 'water.scroll', 'water.dispose'],
  },
  {
    id: 'water.no-repeat',
    file: WATER,
    find: 'map.wrapS = RepeatWrapping;',
    replace: '',
    caseIds: ['water.plane'],
  },
  {
    id: 'water.level',
    file: CONSTANTS,
    find: 'WATER_DROP = 0.15',
    replace: 'WATER_DROP = 0',
    caseIds: ['water.plane'],
  },
  {
    id: 'water.opacity',
    file: CONSTANTS,
    find: 'WATER_OPACITY = 0.84',
    replace: 'WATER_OPACITY = 1',
    caseIds: ['water.plane'],
  },
  {
    id: 'water.dispose-map',
    file: WATER,
    find: '    map.dispose();\n',
    replace: '',
    caseIds: ['water.dispose'],
  },
  {
    id: 'water.dispose-geometry',
    file: WATER,
    find: '    geometry.dispose();\n',
    replace: '',
    caseIds: ['water.dispose'],
  },
  {
    id: 'water.dispose-material',
    file: WATER,
    find: '    material.dispose();\n',
    replace: '',
    caseIds: ['water.dispose'],
  },
  {
    id: 'glow.not-toned',
    file: GLOW,
    find: 'toneMapped: false,',
    replace: '',
    caseIds: ['glow.material'],
  },
  {
    id: 'glow.base-colour',
    file: CONSTANTS,
    find: 'glowBase: [1, 1, 1]',
    replace: 'glowBase: [1, 0, 1]',
    caseIds: ['glow.material'],
  },
  {
    id: 'glow.scale-ignored',
    file: GLOW,
    find: '.makeScale(scale, scale, scale)',
    replace: '.makeScale(1, 1, 1)',
    caseIds: ['glow.instances'],
  },
  {
    id: 'glow.no-colour',
    file: GLOW,
    find: 'mesh.setColorAt(',
    replace: 'Math.max(',
    caseIds: ['glow.instances'],
  },
  {
    id: 'glow.dispose-mesh',
    file: GLOW,
    find: '    mesh.dispose();\n',
    replace: '',
    caseIds: ['glow.dispose', 'env.dispose'],
  },
  {
    id: 'glow.dispose-material',
    file: GLOW,
    find: '    material.dispose();\n',
    replace: '',
    caseIds: ['glow.dispose', 'env.dispose'],
  },
  {
    id: 'sky.radius',
    file: CONSTANTS,
    find: 'SKY_RADIUS = 600',
    replace: 'SKY_RADIUS = 500',
    caseIds: ['sky.dome'],
  },
  {
    id: 'sky.front-side',
    file: SKY,
    find: 'side: BackSide,',
    replace: '',
    caseIds: ['sky.dome'],
  },
  {
    id: 'sky.depth-write',
    file: SKY,
    find: 'depthWrite: false,',
    replace: '',
    caseIds: ['sky.dome'],
  },
  {
    id: 'sky.horizon-lost',
    file: SKY,
    find: 'uHorizon: { value: horizon }',
    replace: 'uHorizon: { value: new Color() }',
    caseIds: ['sky.dome'],
  },
  {
    id: 'sky.no-follow',
    file: SKY,
    find: 'mesh.position.copy(frame.camera.position);',
    replace: 'void frame;',
    caseIds: ['sky.follows'],
  },
  {
    id: 'moon.direction-y',
    file: CONSTANTS,
    find: 'y: 0.42',
    replace: 'y: -0.42',
    caseIds: ['sky.dome', 'moon.follows', 'lights.values'],
  },
  {
    id: 'moon.distance',
    file: CONSTANTS,
    find: 'MOON_DISTANCE = 480',
    replace: 'MOON_DISTANCE = 400',
    caseIds: ['moon.follows'],
  },
  {
    id: 'moon.radius',
    file: CONSTANTS,
    find: 'MOON_RADIUS = 16',
    replace: 'MOON_RADIUS = 12',
    caseIds: ['moon.disc'],
  },
  {
    id: 'moon.no-look',
    file: MOON,
    find: 'mesh.lookAt(camera);',
    replace: '',
    caseIds: ['moon.follows'],
  },
  {
    id: 'moon.no-follow',
    file: MOON,
    find: '.addScaledVector(direction, MOON_DISTANCE)',
    replace: '',
    caseIds: ['moon.follows'],
  },
  {
    id: 'moon.fog',
    file: MOON,
    find: '    fog: false,\n',
    replace: '',
    caseIds: ['moon.disc'],
  },
  {
    id: 'moon.colour',
    file: CONSTANTS,
    find: 'moonDisc: [1.6, 1.55, 1.35]',
    replace: 'moonDisc: [1, 1, 1]',
    caseIds: ['moon.disc'],
  },
  {
    id: 'stars.attenuation',
    file: STARS,
    find: 'sizeAttenuation: false,',
    replace: '',
    caseIds: ['stars.points'],
  },
  {
    id: 'stars.size',
    file: CONSTANTS,
    find: 'STAR_SIZE = 1.6',
    replace: 'STAR_SIZE = 1',
    caseIds: ['stars.points'],
  },
  {
    id: 'stars.opacity',
    file: CONSTANTS,
    find: 'STAR_OPACITY = 0.85',
    replace: 'STAR_OPACITY = 1',
    caseIds: ['stars.points'],
  },
  {
    id: 'stars.fog',
    file: STARS,
    find: '    fog: false,\n',
    replace: '',
    caseIds: ['stars.points'],
  },
  {
    id: 'clouds.opacity',
    file: CONSTANTS,
    find: 'CLOUD_OPACITY = 0.55',
    replace: 'CLOUD_OPACITY = 1',
    caseIds: ['clouds.instances'],
  },
  {
    id: 'clouds.size',
    file: CONSTANTS,
    find: 'CLOUD_SIZE = { x: 4, y: 2, z: 4 }',
    replace: 'CLOUD_SIZE = { x: 4, y: 4, z: 4 }',
    caseIds: ['clouds.instances'],
  },
  {
    id: 'clouds.no-update',
    file: CLOUDS,
    find: '    mesh.position.x = cloudOffsetX(frame.time);',
    replace: '    void frame;',
    caseIds: ['clouds.drift'],
  },
  {
    id: 'clouds.dispose-mesh',
    file: CLOUDS,
    find: '    mesh.dispose();\n',
    replace: '',
    caseIds: ['env.dispose'],
  },
  {
    id: 'fireflies.no-range',
    file: FIREFLIES,
    find: 'geometry.setDrawRange(0, fireflyCountFor(profile, fireflies.seeds.length));',
    replace: '',
    caseIds: ['fireflies.range'],
  },
  {
    id: 'fireflies.range-start',
    file: FIREFLIES,
    find: 'setDrawRange(0,',
    replace: 'setDrawRange(1,',
    caseIds: ['fireflies.range'],
  },
  {
    id: 'fireflies.additive',
    file: FIREFLIES,
    find: 'blending: AdditiveBlending,',
    replace: '',
    caseIds: ['fireflies.range'],
  },
  {
    id: 'fireflies.depth-write',
    file: FIREFLIES,
    find: 'depthWrite: false,',
    replace: '',
    caseIds: ['fireflies.range'],
  },
  {
    id: 'fireflies.scale',
    file: FIREFLIES,
    find: 'uScale.value = frame.viewport.height;',
    replace: 'uScale.value = frame.viewport.width;',
    caseIds: ['fireflies.uniforms'],
  },
  {
    id: 'fireflies.no-time',
    file: FIREFLIES,
    find: 'uTime.value = fireflyTimeFor(frame.time, frame.reducedMotion);',
    replace: 'void frame;',
    caseIds: ['fireflies.uniforms'],
  },
  {
    id: 'lights.all-profiles',
    file: LIGHTS,
    find: "profile === 'desktop'",
    replace: "profile !== 'desktop'",
    caseIds: ['lights.desktop', 'lights.narrow'],
  },
  {
    id: 'lights.lift',
    file: CONSTANTS,
    find: 'decay: 1.6, lift: 2',
    replace: 'decay: 1.6, lift: 0',
    caseIds: ['lights.desktop'],
  },
  {
    id: 'lights.station-count',
    file: CONSTANTS,
    find: 'STATION_LIGHT_COUNT = 9',
    replace: 'STATION_LIGHT_COUNT = 8',
    caseIds: ['lights.desktop'],
  },
  {
    id: 'lights.station-intensity',
    file: CONSTANTS,
    find: 'intensity: 40',
    replace: 'intensity: 30',
    caseIds: ['lights.values'],
  },
  {
    id: 'lights.station-distance',
    file: CONSTANTS,
    find: 'distance: 22',
    replace: 'distance: 20',
    caseIds: ['lights.values'],
  },
  {
    id: 'lights.station-decay',
    file: CONSTANTS,
    find: 'decay: 1.6',
    replace: 'decay: 2',
    caseIds: ['lights.values'],
  },
  {
    id: 'lights.hemisphere',
    file: CONSTANTS,
    find: 'HEMISPHERE_INTENSITY = 1.25',
    replace: 'HEMISPHERE_INTENSITY = 1',
    caseIds: ['lights.values'],
  },
  {
    id: 'lights.moon-intensity',
    file: CONSTANTS,
    find: 'MOON_LIGHT_INTENSITY = 1.5',
    replace: 'MOON_LIGHT_INTENSITY = 1',
    caseIds: ['lights.values'],
  },
  {
    id: 'lights.moon-distance',
    file: CONSTANTS,
    find: 'MOON_LIGHT_DISTANCE = 100',
    replace: 'MOON_LIGHT_DISTANCE = 50',
    caseIds: ['lights.values'],
  },
  {
    id: 'lights.no-ambient',
    file: LIGHTS,
    find: '    new AmbientLight(new Color(AMBIENT_WHITE), AMBIENT_INTENSITY),\n',
    replace: '',
    caseIds: ['lights.desktop', 'lights.narrow', 'lights.values'],
  },
  {
    id: 'env.drop-stars',
    file: ENV,
    find: '    createStarsModule(data.stars),\n',
    replace: '',
    caseIds: ['env.draw-calls', 'env.dispose'],
  },
  {
    id: 'env.drop-moon',
    file: ENV,
    find: '    createMoonModule(),\n',
    replace: '',
    caseIds: ['env.draw-calls', 'env.dispose'],
  },
  {
    id: 'env.drop-fireflies',
    file: ENV,
    find: '    createFirefliesModule(data.fireflies, profile),\n',
    replace: '',
    caseIds: ['env.draw-calls', 'env.dispose'],
  },
  {
    id: 'env.drop-lights',
    file: ENV,
    find: '    createLightsModule(profile, data.stationTops),\n',
    replace: '',
    caseIds: ['env.draw-calls'],
  },
  {
    id: 'env.firefly-profile',
    file: ENV,
    find: 'createFirefliesModule(data.fireflies, profile)',
    replace: "createFirefliesModule(data.fireflies, 'desktop')",
    caseIds: ['env.draw-calls'],
  },
];

export const EQUIVALENT_MUTATIONS: readonly (EnvironmentMutation & Readonly<{ reason: string }>)[] =
  [
    {
      id: 'sky.fog',
      file: SKY,
      find: 'fog: false,',
      replace: '',
      caseIds: ['sky.dome'],
      reason: 'ShaderMaterial.fog defaults to false; the line only mirrors the prototype',
    },
  ];
