import type { WorldActionsCaseId } from '@tests/back/core/world/world-actions.cases';

export type WorldActionsMutation = Readonly<{
  id: string;
  file: string;
  find: string;
  replace: string;
  nth?: number;
  caseIds: readonly WorldActionsCaseId[];
}>;

const ACTIONS = 'src/core/world/world-actions.ts';

const STATIONS = 'src/core/world/stations.ts';

export const WORLD_ACTIONS_MUTATIONS: readonly WorldActionsMutation[] = [
  {
    id: 'stations.swap-order',
    file: STATIONS,
    find: "  'full-cycle',\n  'frontend',",
    replace: "  'frontend',\n  'full-cycle',",
    caseIds: ['world.stations.order'],
  },
  {
    id: 'stations.drop-one',
    file: STATIONS,
    find: "  'this-world',\n",
    replace: '',
    caseIds: ['world.stations.count', 'world.stations.order', 'world.stations.index'],
  },
  {
    id: 'stations.index-off-by-one',
    file: STATIONS,
    find: 'return STATION_IDS.indexOf(id);',
    replace: 'return STATION_IDS.indexOf(id) + 1;',
    caseIds: ['world.stations.index'],
  },
  {
    id: 'stations.at-wraps',
    file: STATIONS,
    find: 'return STATION_IDS[index] ?? null;',
    replace: 'return STATION_IDS[(index + 9) % 9] ?? null;',
    caseIds: ['world.stations.at'],
  },
  {
    id: 'open-text.keeps-menu',
    file: ACTIONS,
    find: "textReason: reason, menu: 'none' };",
    replace: 'textReason: reason, menu: state.menu };',
    caseIds: ['world.actions.open-text'],
  },
  {
    id: 'open-text.wrong-view',
    file: ACTIONS,
    find: "view: 'text', textReason: reason",
    replace: "view: 'boot', textReason: reason",
    caseIds: ['world.actions.open-text'],
  },
  {
    id: 'open-text.always-new',
    file: ACTIONS,
    find: "  if (state.view === 'text' && state.textReason === reason && state.menu === 'none') {\n    return state;\n  }\n\n",
    replace: '',
    caseIds: ['world.actions.open-text.same'],
  },
  {
    id: 'open-text.ignores-reason-change',
    file: ACTIONS,
    find: "state.view === 'text' && state.textReason === reason && state.menu === 'none'",
    replace: "state.view === 'text' && state.menu === 'none'",
    caseIds: ['world.actions.open-text.same'],
  },
  {
    id: 'open-world.keeps-reason',
    file: ACTIONS,
    find: "view: 'world', textReason: null };",
    replace: "view: 'world', textReason: state.textReason };",
    caseIds: ['world.actions.open-world'],
  },
  {
    id: 'open-world.always-new',
    file: ACTIONS,
    find: "  if (state.view === 'world' && state.textReason === null) {\n    return state;\n  }\n\n",
    replace: '',
    caseIds: ['world.actions.open-world'],
  },
  {
    id: 'open-world.resets-visited',
    file: ACTIONS,
    find: "view: 'world', textReason: null };",
    replace: "view: 'world', textReason: null, visited: [] };",
    caseIds: ['world.actions.keep-state-on-switch'],
  },
  {
    id: 'open-text.resets-flight',
    file: ACTIONS,
    find: "view: 'text', textReason: reason, menu: 'none' };",
    replace: "view: 'text', textReason: reason, menu: 'none', flight: { mode: 'free' } };",
    caseIds: ['world.actions.keep-state-on-switch'],
  },
  {
    id: 'available.never-stored',
    file: ACTIONS,
    find: 'return { ...state, worldAvailable: available };',
    replace: 'return { ...state, worldAvailable: false };',
    caseIds: ['world.actions.world-available'],
  },
  {
    id: 'available.always-new',
    file: ACTIONS,
    find: '  if (state.worldAvailable === available) {\n    return state;\n  }\n\n',
    replace: '',
    caseIds: ['world.actions.world-available'],
  },
  {
    id: 'start-loading.any-status',
    file: ACTIONS,
    find: "if (state.boot.status !== 'idle') {",
    replace: "if (state.boot.status === 'failed') {",
    caseIds: ['world.actions.start-loading'],
  },
  {
    id: 'start-loading.engine-true',
    file: ACTIONS,
    find: "status: 'loading', worker: 0, engine: false",
    replace: "status: 'loading', worker: 0, engine: true",
    caseIds: ['world.actions.start-loading'],
  },
  {
    id: 'progress.no-upper-clamp',
    file: ACTIONS,
    find: 'Math.min(1, Math.max(0, value))',
    replace: 'Math.max(0, value)',
    caseIds: ['world.actions.worker-progress'],
  },
  {
    id: 'progress.no-lower-clamp',
    file: ACTIONS,
    find: 'Math.min(1, Math.max(0, value))',
    replace: 'Math.min(1, value)',
    caseIds: ['world.actions.worker-progress'],
  },
  {
    id: 'progress.any-status',
    file: ACTIONS,
    find: "if (state.boot.status !== 'loading') {\n    return state;\n  }\n\n  const worker",
    replace: "if (state.boot.status === 'failed') {\n    return state;\n  }\n\n  const worker",
    caseIds: ['world.actions.worker-progress.not-loading'],
  },
  {
    id: 'engine.any-status',
    file: ACTIONS,
    find: "if (state.boot.status !== 'loading' || state.boot.engine) {",
    replace:
      "if (state.boot.status !== 'loading' && state.boot.status !== 'idle' || state.boot.engine) {",
    caseIds: ['world.actions.engine-loaded'],
  },
  {
    id: 'engine.drops-worker',
    file: ACTIONS,
    find: 'boot: { ...state.boot, engine: true }',
    replace: "boot: { status: 'loading', worker: 0, engine: true }",
    caseIds: ['world.actions.engine-loaded'],
  },
  {
    id: 'ready.from-any',
    file: ACTIONS,
    find: "export const markReady = (state: WorldSnapshot): WorldSnapshot => {\n  if (state.boot.status !== 'loading') {",
    replace:
      "export const markReady = (state: WorldSnapshot): WorldSnapshot => {\n  if (state.boot.status === 'failed') {",
    caseIds: ['world.actions.mark-ready'],
  },
  {
    id: 'take-off.wrong-boot',
    file: ACTIONS,
    find: "boot: { status: 'running' },",
    replace: "boot: { status: 'ready' },",
    caseIds: ['world.actions.take-off'],
  },
  {
    id: 'take-off.keeps-flight',
    file: ACTIONS,
    find: "    flight: { mode: 'intro' },\n    sound: true,",
    replace: '    flight: state.flight,\n    sound: true,',
    caseIds: ['world.actions.take-off'],
  },
  {
    id: 'take-off.keeps-menu',
    file: ACTIONS,
    find: "    menu: 'none',\n    flash: { seq: (state.flash?.seq ?? 0) + 1, kind: 'take-off' },",
    replace:
      "    menu: state.menu,\n    flash: { seq: (state.flash?.seq ?? 0) + 1, kind: 'take-off' },",
    caseIds: ['world.actions.take-off'],
  },
  {
    id: 'take-off.no-flash',
    file: ACTIONS,
    find: "    flash: { seq: (state.flash?.seq ?? 0) + 1, kind: 'take-off' },",
    replace: '    flash: state.flash,',
    caseIds: [
      'world.actions.take-off',
      'world.actions.take-off.flash-seq',
      'world.actions.flash-send',
    ],
  },
  {
    id: 'take-off.sound-stays-off',
    file: ACTIONS,
    find: '    sound: true,\n    menu',
    replace: '    sound: state.sound,\n    menu',
    caseIds: ['world.actions.take-off.sound'],
  },
  {
    id: 'take-off.from-any',
    file: ACTIONS,
    find: "if (state.boot.status !== 'ready') {",
    replace: "if (state.boot.status === 'running') {",
    caseIds: ['world.actions.take-off.not-ready'],
  },
  {
    id: 'take-off.seq-constant',
    file: ACTIONS,
    find: "flash: { seq: (state.flash?.seq ?? 0) + 1, kind: 'take-off' },",
    replace: "flash: { seq: 1, kind: 'take-off' },",
    caseIds: ['world.actions.take-off.flash-seq'],
  },
  {
    id: 'fail.second-overrides',
    file: ACTIONS,
    find: "reason: WorldFailReason): WorldSnapshot => {\n  if (state.boot.status === 'failed') {\n    return state;\n  }\n\n",
    replace: 'reason: WorldFailReason): WorldSnapshot => {\n',
    caseIds: ['world.actions.fail.first-reason-wins'],
  },
  {
    id: 'fail.no-webgl2-as-failed',
    file: ACTIONS,
    find: "reason === 'no-webgl2' ? 'no-webgl2' : 'failed'",
    replace: "'failed'",
    caseIds: ['world.actions.fail.no-webgl2'],
  },
  {
    id: 'fail.all-as-no-webgl2',
    file: ACTIONS,
    find: "reason === 'no-webgl2' ? 'no-webgl2' : 'failed'",
    replace: "'no-webgl2'",
    caseIds: ['world.actions.fail.other'],
  },
  {
    id: 'fail.boot-reason-dropped',
    file: ACTIONS,
    find: "boot: { status: 'failed', reason },",
    replace: "boot: { status: 'failed', reason: 'timeout' },",
    caseIds: ['world.actions.fail.no-webgl2', 'world.actions.fail.other'],
  },
  {
    id: 'fail.stays-in-view',
    file: ACTIONS,
    find: "    view: 'text',\n    textReason: reason",
    replace: '    view: state.view,\n    textReason: reason',
    caseIds: ['world.actions.fail.no-webgl2', 'world.actions.fail.other'],
  },
  {
    id: 'fail.world-stays-available',
    file: ACTIONS,
    find: '    worldAvailable: false,\n    menu',
    replace: '    worldAvailable: state.worldAvailable,\n    menu',
    caseIds: ['world.actions.fail.no-webgl2', 'world.actions.fail.other'],
  },
  {
    id: 'fail.keeps-menu',
    file: ACTIONS,
    find: "    worldAvailable: false,\n    menu: 'none',",
    replace: '    worldAvailable: false,\n    menu: state.menu,',
    caseIds: ['world.actions.fail.no-webgl2', 'world.actions.fail.from-running'],
  },
  {
    id: 'menu.not-stored',
    file: ACTIONS,
    find: 'return { ...state, menu };',
    replace: "return { ...state, menu: 'none' };",
    caseIds: ['world.actions.set-menu'],
  },
  {
    id: 'menu.always-new',
    file: ACTIONS,
    find: '  if (state.menu === menu) {\n    return state;\n  }\n\n',
    replace: '',
    caseIds: ['world.actions.set-menu'],
  },
  {
    id: 'sound.not-stored',
    file: ACTIONS,
    find: 'return { ...state, sound: on };',
    replace: 'return { ...state, sound: true };',
    caseIds: ['world.actions.set-sound'],
  },
  {
    id: 'sound.always-new',
    file: ACTIONS,
    find: '  if (state.sound === on) {\n    return state;\n  }\n\n',
    replace: '',
    caseIds: ['world.actions.set-sound'],
  },
  {
    id: 'flight.always-new',
    file: ACTIONS,
    find: '  if (sameFlight(state.flight, phase)) {\n    return state;\n  }\n\n',
    replace: '',
    caseIds: ['world.actions.set-flight'],
  },
  {
    id: 'flight.ignores-target',
    file: ACTIONS,
    find: 'return a.target === b.target;',
    replace: 'return true;',
    caseIds: ['world.actions.set-flight'],
  },
  {
    id: 'flight.ignores-station',
    file: ACTIONS,
    find: 'return a.station === b.station;',
    replace: 'return true;',
    caseIds: ['world.actions.set-flight'],
  },
  {
    id: 'flight.ignores-mode',
    file: ACTIONS,
    find: '  if (a.mode !== b.mode) {\n    return false;\n  }\n\n',
    replace: '',
    caseIds: ['world.actions.set-flight'],
  },
  {
    id: 'visited.prepend',
    file: ACTIONS,
    find: 'visited: [...state.visited, id]',
    replace: 'visited: [id, ...state.visited]',
    caseIds: ['world.actions.visited.first-order'],
  },
  {
    id: 'visited.sorted',
    file: ACTIONS,
    find: 'visited: [...state.visited, id]',
    replace: 'visited: [...state.visited, id].sort()',
    caseIds: ['world.actions.visited.first-order'],
  },
  {
    id: 'visited.no-dedupe',
    file: ACTIONS,
    find: '  if (state.visited.includes(id)) {\n    return state;\n  }\n\n',
    replace: '',
    caseIds: ['world.actions.visited.dedupe', 'world.actions.visited.count'],
  },
  {
    id: 'visited.mutates',
    file: ACTIONS,
    find: 'return { ...state, visited: [...state.visited, id] };',
    replace: '(state.visited as StationId[]).push(id);\n\n  return { ...state };',
    caseIds: ['world.actions.pure'],
  },
  {
    id: 'input.not-stored',
    file: ACTIONS,
    find: 'return { ...state, inputUsed: true };',
    replace: 'return { ...state };',
    caseIds: ['world.actions.input-used'],
  },
  {
    id: 'input.always-new',
    file: ACTIONS,
    find: '  if (state.inputUsed) {\n    return state;\n  }\n\n',
    replace: '',
    caseIds: ['world.actions.input-used'],
  },
  {
    id: 'slow.not-stored',
    file: ACTIONS,
    find: 'return { ...state, slow: true };',
    replace: 'return { ...state };',
    caseIds: ['world.actions.slow'],
  },
  {
    id: 'slow.always-new',
    file: ACTIONS,
    find: '  if (state.slow) {\n    return state;\n  }\n\n',
    replace: '',
    caseIds: ['world.actions.slow'],
  },
  {
    id: 'flash-send.wrong-kind',
    file: ACTIONS,
    find: "kind: 'send' }",
    replace: "kind: 'take-off' }",
    caseIds: ['world.actions.flash-send'],
  },
  {
    id: 'flash-send.seq-constant',
    file: ACTIONS,
    find: "flash: { seq: (state.flash?.seq ?? 0) + 1, kind: 'send' }",
    replace: "flash: { seq: 1, kind: 'send' }",
    caseIds: ['world.actions.flash-send'],
  },
  {
    id: 'progress.mutates-boot',
    file: ACTIONS,
    find: 'return { ...state, boot: { ...state.boot, worker } };',
    replace: 'state.boot.worker = worker;\n\n  return { ...state };',
    caseIds: ['world.actions.pure'],
  },
];
