import type { SiteCopy } from '@/content/content.types';

export const SITE_COPY: SiteCopy = {
  title: 'Vitalii Vorynka · Full-stack Developer: Vue, React, Node.js',
  ogTitle: 'Vitalii Vorynka · Full-stack Developer, AI Engineer',
  description:
    'Full-stack developer, 7+ years in production. React, Next.js, Vue, Node.js, NestJS, Docker, CI/CD, LLMs and AI agents. A 3D world portfolio with a text version.',
  ogAlt: 'Vitalii Vorynka, full-stack developer, above a night voxel world',
  siteName: 'Vitalii Vorynka',
  keywords: [
    'Vitalii Vorynka',
    'full-stack developer',
    'AI engineer',
    'React developer',
    'Next.js',
    'Vue developer',
    'Nuxt',
    'Node.js developer',
    'NestJS',
    'TypeScript',
    'LLM integration',
    'RAG',
    'AI agents',
    'Claude Code',
    'MCP',
    'Docker',
    'CI/CD',
    'Kyiv',
    'Ukraine',
    'remote',
  ],
  person: {
    name: 'Vitalii Vorynka',
    jobTitle: 'Full-stack Developer, AI Engineer',
    sameAs: ['https://www.linkedin.com/in/vitaliy-vorynka-7b6005142'],
    knowsAbout: [
      'TypeScript',
      'React',
      'Next.js',
      'Vue',
      'Nuxt',
      'Node.js',
      'NestJS',
      'Express',
      'PostgreSQL',
      'Redis',
      'RabbitMQ',
      'Docker',
      'CI/CD',
      'LLM integration',
      'RAG',
      'AI agents',
      'MCP',
    ],
    address: { locality: 'Kyiv', country: 'UA' },
  },
};
