import type { StationsCopy } from '@/content/content.types';

const LINKEDIN_HREF = 'https://www.linkedin.com/in/vitaliy-vorynka-7b6005142';

const named = (names: readonly string[]) => {
  return names.map((name) => {
    return { name, years: null };
  });
};

export const STATIONS_COPY: StationsCopy = {
  'home-base': {
    id: 'home-base',
    label: 'Home base',
    tag: 'Pilot on duty',
    title: 'Vitalii Vorynka',
    role: 'Full-stack Developer · AI Engineer',
    lede: 'Builds web products end to end: interface, backend, deploy. 7+ years in production, 20+ projects.',
    contactCta: 'Contact',
    linkedin: { label: 'LinkedIn', href: LINKEDIN_HREF },
    stats: [
      { value: '7+', caption: 'years in production' },
      { value: '20+', caption: 'projects' },
    ],
    chips: [
      'TypeScript',
      'React',
      'Next.js',
      'Vue',
      'Nuxt',
      'Node.js',
      'NestJS',
      'Express',
      'Docker',
      'Claude Code',
    ],
  },
  'full-cycle': {
    id: 'full-cycle',
    label: 'Full cycle',
    tag: 'Full cycle',
    title: 'From idea to production',
    lede: 'Takes an idea from zero to a working product.',
    items: [
      'Breaks down the idea and the task, researches the market and the technology.',
      'Writes the spec: what to build, on what, in what order.',
      'Builds the frontend and the backend.',
      'Brings it to an MVP and ships it to production.',
      'Adds AI when the product needs it.',
    ],
    chips: [],
    result: { value: 'Idea to MVP', caption: 'Full cycle, start to finish' },
  },
  frontend: {
    id: 'frontend',
    label: 'Frontend',
    tag: 'Frontend · 7+ years',
    title: 'Interfaces in React and Vue',
    lede: 'Main focus. Works as a React developer and a Vue developer, with Next.js and Nuxt, all in TypeScript.',
    items: [
      'The interface adapts to user rights: roles, permissions, an access check on every screen.',
      'Micro-frontends built from widgets, with real-time data updates.',
      'A custom UI kit on Radix, documented in Storybook.',
      'Sign-in through Keycloak (OIDC). Two languages, Ukrainian and English, 600+ keys.',
      'Large admin panels: tables with server-side filtering and sorting, one form architecture for every section.',
      'SEO: SSR and SSG, metadata, Open Graph, sitemap, robots, schema.org markup, Core Web Vitals. This site scores Lighthouse SEO 100.',
      'Accessibility: keyboard navigation, a no-animation mode (prefers-reduced-motion), a text version without WebGL, axe checks in tests. This site scores Lighthouse Accessibility 100.',
    ],
    chips: [
      'TypeScript',
      'React',
      'Next.js',
      'Vue 3',
      'Nuxt 3',
      'Pinia',
      'Redux Toolkit',
      'Zustand',
      'TanStack Query',
      'Tailwind',
      'Radix UI',
      'Storybook',
      'SEO',
      'Accessibility',
    ],
    result: { value: '7+ yrs', caption: 'Frontend in production' },
  },
  backend: {
    id: 'backend',
    label: 'Backend',
    tag: 'Backend',
    title: 'Services on Node.js',
    lede: 'Node.js developer for the backend: NestJS and Express, APIs, queues, databases, auth.',
    items: [
      'Microservices: Node.js and Python services talk over RabbitMQ.',
      'Redis holds one auth session for all services: one token, one refresh.',
      'PostgreSQL: designs the schema, tables and indexes. Also MongoDB and Prisma.',
      'Load balancing, load testing, scaling.',
      'REST, GraphQL, WebSockets. Auth with JWT, OAuth, Keycloak.',
      'Third-party integrations: SMTP mail (Nodemailer, Resend), AWS S3 for files, LLM APIs (OpenAI, Anthropic), Keycloak, Cloudflare Turnstile, data collection from external APIs.',
    ],
    chips: [
      'Node.js',
      'NestJS',
      'Express',
      'RabbitMQ',
      'Redis',
      'PostgreSQL',
      'MongoDB',
      'AWS S3',
      'SMTP',
    ],
    result: { value: 'Node.js', caption: 'NestJS and Express APIs, queues, auth' },
  },
  ai: {
    id: 'ai',
    label: 'AI',
    tag: 'AI integration',
    title: 'AI in the product and the workflow',
    lede: 'Builds LLMs into products and sets up AI-assisted development for a team.',
    items: [
      'LLM in the product: a separate service, connected through a queue, with OpenAI and Anthropic.',
      'Sets up RAG and AI agents.',
      'A harness for Claude Code: agents, skills, mods, guard hooks, evals.',
      'MCP: connects ready-made servers and writes custom ones.',
      'Token cost tuning: which model for which task, what to keep in context.',
    ],
    chips: [
      'Claude Code',
      'LLM',
      'RAG',
      'AI agents',
      'MCP',
      'Skills',
      'Hooks',
      'Evals',
      'OpenAI',
      'Anthropic',
    ],
    result: { value: 'Own MCP', caption: 'Custom MCP servers, skills and hooks' },
  },
  systems: {
    id: 'systems',
    label: 'Systems',
    tag: 'Stack',
    title: 'The working stack',
    groups: [
      {
        title: 'Frontend',
        years: null,
        items: named([
          'TypeScript',
          'React',
          'Next.js',
          'Vue 3',
          'Nuxt 3',
          'Pinia',
          'Redux Toolkit',
          'Zustand',
          'TanStack Query',
          'Tailwind',
          'SCSS',
        ]),
      },
      {
        title: 'Backend',
        years: null,
        items: named([
          'Node.js',
          'NestJS',
          'Express',
          'REST',
          'GraphQL',
          'WebSockets',
          'RabbitMQ',
          'Redis',
          'PostgreSQL',
          'MongoDB',
        ]),
      },
      {
        title: 'Integrations',
        years: null,
        items: named(['SMTP', 'AWS S3', 'OpenAI', 'Anthropic', 'Keycloak', 'Cloudflare Turnstile']),
      },
      {
        title: 'DevOps',
        years: null,
        items: named(['Docker', 'CI/CD', 'AWS S3', 'Cloudflare']),
      },
      {
        title: 'AI',
        years: null,
        items: named(['Claude Code', 'LLM integration', 'RAG', 'AI agents']),
      },
      {
        title: 'Tools and 3D',
        years: null,
        items: named([
          'Playwright',
          'Storybook',
          'Vite',
          'Webpack',
          'Figma',
          'Three.js',
          'WebGL',
          'Canvas',
        ]),
      },
    ],
  },
  deploy: {
    id: 'deploy',
    label: 'Deploy',
    tag: 'DevOps',
    title: 'Ships to production',
    lede: 'Takes the code all the way to production: Docker, CI/CD, server, domain, mail.',
    items: [
      'Docker images and compose, separate dev and prod environments.',
      'CI/CD: a push to dev deploys the test stand, prod goes out by manual run.',
      'A DigitalOcean server behind Cloudflare: proxy, SSL Full strict, Turnstile against spam.',
      'Mail from the domain: an SMTP service, a verified domain, DMARC. The site form sends its messages through it.',
      'API proxying and caching for Next.js, files in AWS S3.',
    ],
    chips: ['Docker', 'CI/CD', 'DigitalOcean', 'Cloudflare', 'Caddy', 'AWS S3'],
    result: { value: 'Dev + prod', caption: 'Separate environments, CI/CD deploys' },
  },
  'this-world': {
    id: 'this-world',
    label: 'This world',
    tag: 'How it was built',
    title: 'This site is a project too',
    lede: 'A 3D world on WebGL. Built by one developer with an AI assistant, using the same agent workflow.',
    items: [
      'Three.js and WebGL. The voxel world is generated in a web worker.',
      'Next.js around it: a text version for search engines and devices without WebGL.',
      'A contact form with spam protection: per-IP limits, honeypot, Turnstile.',
    ],
    chips: [],
    result: { value: '1 + AI', caption: 'One developer and an AI assistant' },
  },
  contact: {
    id: 'contact',
    label: 'Contact',
    tag: 'Open channel',
    title: 'Open a channel',
    lede: 'Have an idea, a role or a project? Send a message. Every message gets a reply. Available now, remote or in Kyiv, Ukraine.',
    email: 'vitaliivorynka@gmail.com',
    copy: { idle: 'Copy', done: 'Copied' },
    linkedin: { label: 'linkedin.com/in/vitaliy-vorynka-7b6005142', href: LINKEDIN_HREF },
  },
};
