import type { StationsCopy } from '@/content/content.types';

const LINKEDIN_HREF = 'https://www.linkedin.com/in/vitaliy-vorynka-7b6005142';

export const STATIONS_COPY: StationsCopy = {
  'home-base': {
    id: 'home-base',
    label: 'Home base',
    tag: 'Pilot on duty',
    title: 'Vitalii Vorynka',
    role: 'Full-stack dev with AI engineering',
    lede: 'Builds interfaces and the services behind them. Runs AI agents as part of the workflow.',
    contactCta: 'Contact',
    cv: { label: 'Download CV' },
    linkedin: { label: 'LinkedIn', href: LINKEDIN_HREF },
    stats: [
      { value: '7+', caption: 'years in production' },
      { value: '2+', caption: 'years as a tech lead' },
    ],
    chips: ['TypeScript', 'React', 'Next.js', 'Vue', 'Nuxt', 'Node.js', 'Three.js', 'Claude Code'],
  },
  'llm-product': {
    id: 'llm-product',
    label: 'LLM product',
    tag: 'Mission 1 of 3',
    title: 'An LLM product from zero',
    lede: 'Designed the full stack and led the build, from the first commit to delivery on time.',
    items: [
      'Architecture front and back: React, NestJS, RabbitMQ to an LLM service.',
      'Redis keeps one shared auth session, so every client service uses one token.',
      'Designed the PostgreSQL schema, tables and indexes.',
      'Code review, refactoring plans and technology choices.',
    ],
    chips: ['React', 'NestJS', 'RabbitMQ', 'Redis', 'PostgreSQL', 'Docker'],
    result: { value: 'On time', caption: 'delivered as the tech lead' },
  },
  'marketplace-chat': {
    id: 'marketplace-chat',
    label: 'Marketplace chat',
    tag: 'Mission 2 of 3',
    title: 'Chat and video player, live',
    lede: 'Real-time chat and a browser video player for a Vue 2 marketplace. Both went live to real users.',
    items: [
      'Wrote the chat and messaging layer on WebSockets and RTM.',
      'Built the video player that went live on the platform.',
      'Shipped marketplace features in Vue 2 and Vuex.',
    ],
    chips: ['Vue 2', 'Vuex', 'WebSockets', 'RTM', 'JavaScript'],
    result: { value: 'Live', caption: 'chat and player in production' },
  },
  'admin-app': {
    id: 'admin-app',
    label: 'Admin app',
    tag: 'Mission 3 of 3',
    title: 'An admin app with 46 pages',
    lede: 'The frontend for a tracking platform: 19 business domains behind one admin interface.',
    items: [
      'Data tables with server-side filtering and sorting.',
      'One form architecture shared across all the domains.',
      'Role-based access across the whole app.',
    ],
    chips: ['Nuxt 3', 'Pinia', 'Nuxt UI', 'Tailwind 4', 'TypeScript'],
    result: { value: '46 pages', caption: 'across 19 business domains' },
  },
  'ai-engineering': {
    id: 'ai-engineering',
    label: 'AI engineering',
    tag: 'AI engineering',
    title: 'Builds with agent workflows',
    lede: 'Designs development workflows from AI agents: specs first, guard rails around, evals on top.',
    items: [
      'Agent workflows in Claude Code: planning, building and review split between agents.',
      'Agents set up for security: no secret reads, no git writes, nothing leaks outside the project.',
      'Evals prove the guards hold. Specs come before code.',
      'In products: RAG, AI agents, LLM integration with OpenAI and Anthropic.',
    ],
    chips: ['Claude Code', 'Agents', 'Specs', 'Guard hooks', 'Evals', 'RAG'],
    result: { value: 'Daily', caption: 'Claude Code is the main tool' },
  },
  systems: {
    id: 'systems',
    label: 'Systems',
    tag: 'Systems',
    title: 'What is in the cockpit',
    lede: 'Frontend first, backend when the product needs it, security in every layer.',
    groups: [
      {
        title: 'Frontend',
        years: '7+ yrs',
        items: [
          { name: 'TypeScript', years: null },
          { name: 'React', years: null },
          { name: 'Next.js', years: null },
          { name: 'Vue 3', years: null },
          { name: 'Nuxt 3', years: null },
          { name: 'Tailwind', years: null },
          { name: 'Three.js', years: null },
          { name: 'WebGL', years: null },
          { name: 'Canvas', years: null },
        ],
      },
      {
        title: 'Backend',
        years: null,
        items: [
          { name: 'Node.js', years: '2 yrs' },
          { name: 'NestJS', years: null },
          { name: 'REST', years: null },
          { name: 'WebSockets', years: null },
          { name: 'RabbitMQ', years: null },
          { name: 'Redis', years: null },
          { name: 'PostgreSQL', years: null },
        ],
      },
      {
        title: 'Architecture and security',
        years: null,
        items: [
          { name: 'Schema design', years: null },
          { name: 'Indexes', years: null },
          { name: 'Rate limiting', years: null },
          { name: 'Input validation', years: null },
          { name: 'Injection-safe queries', years: null },
          { name: 'DDoS-aware endpoints', years: null },
          { name: 'Secure dev setup', years: null },
        ],
      },
      {
        title: 'AI',
        years: null,
        items: [
          { name: 'Claude Code', years: null },
          { name: 'LLM integration', years: null },
          { name: 'RAG', years: null },
          { name: 'AI agents', years: null },
          { name: 'Prompt engineering', years: null },
        ],
      },
      {
        title: 'Tooling',
        years: null,
        items: [
          { name: 'Docker', years: null },
          { name: 'CI/CD', years: null },
          { name: 'Playwright', years: null },
          { name: 'Storybook', years: null },
          { name: 'Vite', years: null },
          { name: 'Webpack', years: null },
          { name: 'Figma', years: null },
          { name: 'AWS S3', years: null },
        ],
      },
    ],
  },
  'flight-log': {
    id: 'flight-log',
    label: 'Flight log',
    tag: 'Flight log',
    title: 'Routes flown so far',
    entries: [
      {
        years: '2024–26',
        role: 'Tech lead',
        summary: "LLM product from scratch, Next.js frontends, the team's agent workflow.",
      },
      {
        years: '2022–24',
        role: 'Frontend engineer',
        summary: 'Vue 2 marketplace: real-time chat and a video player, live to real users.',
      },
      {
        years: '2021–22',
        role: 'Team lead',
        summary: '2 client projects at an outsourcing company, delivered on schedule.',
      },
      {
        years: '2020–21',
        role: 'Frontend developer',
        summary: 'A live client product, SPAs and admin panels.',
      },
      {
        years: '2018–20',
        role: 'Freelance developer',
        summary: 'International clients, repeat work.',
      },
      {
        years: '2015–18',
        role: 'Public service, Ukraine',
        summary: 'Left in 2018 to start in development.',
      },
    ],
  },
  'this-world': {
    id: 'this-world',
    label: 'This world',
    tag: 'How this was built',
    title: 'You are flying the proof',
    lede: 'A live WebGL scene. Built together with an AI assistant through the same agent workflow.',
    items: [
      'Three.js and WebGL, GLSL shaders, procedural voxel terrain, Next.js around it.',
      'GSAP for motion, Web Audio for sound, plain HTML under the scene for the text version.',
      'One developer and one AI assistant, working through agents, specs and guard hooks.',
    ],
    chips: ['Three.js', 'WebGL', 'GLSL', 'GSAP', 'Web Audio', 'Next.js'],
    result: { value: '1 + AI', caption: 'one developer, one AI assistant' },
  },
  contact: {
    id: 'contact',
    label: 'Contact',
    tag: 'Open channel',
    title: 'Open a channel',
    lede: 'A role or a project in mind? Send a message. Every message gets a reply.',
    email: 'vitaliivorynka@gmail.com',
    copy: { idle: 'Copy', done: 'Copied' },
    linkedin: { label: 'linkedin.com/in/vitaliy-vorynka-7b6005142', href: LINKEDIN_HREF },
  },
};
