import type { DockingCaseId } from '@tests/back/scene/flight/docking.cases';

export type DockingMutation = Readonly<{
  id: string;
  file: string;
  find: string;
  replace: string;
  nth?: number;
  caseIds: readonly DockingCaseId[];
}>;

const DOCKING = 'src/scene/flight/docking.ts';
const CONSTANTS = 'src/scene/flight/flight.constants.ts';

export const DOCKING_MUTATIONS: readonly DockingMutation[] = [
  {
    id: 'link-range.wider',
    file: CONSTANTS,
    find: 'LINK_RANGE = 15',
    replace: 'LINK_RANGE = 16',
    caseIds: ['docking.free.link-range'],
  },
  {
    id: 'unlink-range.shorter',
    file: CONSTANTS,
    find: 'UNLINK_RANGE = 24',
    replace: 'UNLINK_RANGE = 20',
    caseIds: ['docking.takeoff.cooldown'],
  },
  {
    id: 'cancel.threshold',
    file: CONSTANTS,
    find: 'AUTOPILOT_CANCEL = 0.35',
    replace: 'AUTOPILOT_CANCEL = 0.5',
    caseIds: ['docking.autopilot.cancel'],
  },
  {
    id: 'cancel.inclusive',
    file: DOCKING,
    find: 'steer.magnitude > AUTOPILOT_CANCEL',
    replace: 'steer.magnitude >= AUTOPILOT_CANCEL',
    caseIds: ['docking.autopilot.cancel'],
  },
  {
    id: 'cooldown.not-set',
    file: DOCKING,
    find: '    state.cooldown |= bit(mode.station);\n    state.mode = freeMode();',
    replace: '    state.mode = freeMode();',
    caseIds: ['docking.takeoff', 'docking.takeoff.cooldown'],
  },
  {
    id: 'cooldown.not-set-on-autopilot',
    file: DOCKING,
    find: "    state.cooldown |= bit(mode.station);\n    events.push({ type: 'undocked'",
    replace: "    events.push({ type: 'undocked'",
    caseIds: ['docking.autopilot.while-docked'],
  },
  {
    id: 'cooldown.never-released',
    file: DOCKING,
    find: '        state.cooldown &= ~bit(index);',
    replace: '        state.cooldown |= 0;',
    caseIds: ['docking.takeoff.cooldown'],
  },
  {
    id: 'cooldown.target-kept',
    file: DOCKING,
    find: '  state.cooldown &= ~bit(target);\n',
    replace: '',
    caseIds: ['docking.autopilot.clears-target-cooldown'],
  },
  {
    id: 'visited.counted-twice',
    file: DOCKING,
    find: 'const firstVisit = !hasBit(state.visited, index);',
    replace: 'const firstVisit = true;',
    caseIds: [
      'docking.takeoff.cooldown',
      'docking.visited.count',
      'docking.autopilot.clears-target-cooldown',
    ],
  },
  {
    id: 'visited.not-recorded',
    file: DOCKING,
    find: '  state.visited |= bit(index);\n',
    replace: '',
    caseIds: ['docking.intro-done.docks-home', 'docking.visited.count'],
  },
  {
    id: 'autopilot.docks-passed-station',
    file: DOCKING,
    find: "const isTarget = mode.kind === 'autopilot' && mode.target === index;",
    replace: "const isTarget = mode.kind === 'autopilot';",
    caseIds: ['docking.autopilot.passes-non-target'],
  },
  {
    id: 'intro.docks',
    file: DOCKING,
    find: 'if (!state.introDone || !(distance < LINK_RANGE)) {',
    replace: 'if (!(distance < LINK_RANGE)) {',
    caseIds: ['docking.intro.never-docks'],
  },
  {
    id: 'docked.steer-undocks',
    file: DOCKING,
    find: "if (cancels && state.mode.kind === 'autopilot') {",
    replace: "if (cancels && state.mode.kind !== 'free') {",
    caseIds: ['docking.docked.ignores-steer'],
  },
  {
    id: 'home.dock-distance',
    file: CONSTANTS,
    find: 'HOME_DOCK_DISTANCE = 26',
    replace: 'HOME_DOCK_DISTANCE = 10',
    caseIds: ['docking.intro-done.docks-home'],
  },
  {
    id: 'dock.height',
    file: CONSTANTS,
    find: 'DOCK_HEIGHT = 6',
    replace: 'DOCK_HEIGHT = 7',
    caseIds: ['docking.dock-point.degenerate'],
  },
  {
    id: 'dock.ground-clearance',
    file: CONSTANTS,
    find: 'DOCK_GROUND_CLEARANCE = 4',
    replace: 'DOCK_GROUND_CLEARANCE = 3',
    caseIds: ['docking.dock-point'],
  },
  {
    id: 'dock.degenerate-guard',
    file: DOCKING,
    find: '    ox = 0;\n    oz = 1;',
    replace: '    ox = 1;\n    oz = 0;',
    caseIds: ['docking.dock-point.degenerate'],
  },
  {
    id: 'orbit-side.flipped',
    file: DOCKING,
    find: '>= 0 ? 1 : -1;',
    replace: '>= 0 ? -1 : 1;',
    caseIds: ['docking.intro-done.docks-home', 'docking.dock-point'],
  },
  {
    id: 'takeoff.during-intro',
    file: DOCKING,
    find: '  if (!state.introDone) {\n    return NO_EVENTS;\n  }',
    replace: '',
    caseIds: ['docking.autopilot.invalid'],
  },
  {
    id: 'autopilot.current-undocks',
    file: DOCKING,
    find: "  if (mode.kind === 'docked' && mode.station === target) {\n    return NO_EVENTS;\n  }",
    replace: '',
    caseIds: ['docking.autopilot.current'],
  },
  {
    id: 'autopilot.index-unchecked',
    file: DOCKING,
    find: '  if (!isStationIndex(target, stations)) {\n    return NO_EVENTS;\n  }',
    replace: '',
    caseIds: ['docking.autopilot.invalid'],
  },
  {
    id: 'reset.keeps-cooldown',
    file: DOCKING,
    find: '  state.cooldown = 0;\n',
    replace: '',
    caseIds: ['docking.reset'],
  },
  {
    id: 'reset.keeps-mode',
    file: DOCKING,
    find: '  state.mode = freeMode();\n  state.orbitSide = 1;',
    replace: '  state.orbitSide = 1;',
    caseIds: ['docking.reset'],
  },
  {
    id: 'reset.no-placement',
    file: DOCKING,
    find: '    placeOnOrbit(plane, home, ORBIT_START_ANGLE);',
    replace: '    plane.speed = 0;',
    caseIds: ['docking.reset'],
  },
  {
    id: 'takeoff.grace-distance',
    file: CONSTANTS,
    find: 'TAKEOFF_GRACE_DISTANCE = LINK_RANGE',
    replace: 'TAKEOFF_GRACE_DISTANCE = 14',
    caseIds: ['docking.takeoff.grace'],
  },
  {
    id: 'takeoff.grace-inclusive',
    file: DOCKING,
    find: '< TAKEOFF_GRACE_DISTANCE',
    replace: '<= TAKEOFF_GRACE_DISTANCE',
    caseIds: ['docking.takeoff.grace'],
  },
  {
    id: 'takeoff.grace-ignored',
    file: DOCKING,
    find: "const isFree = mode.kind === 'free' && !grace;",
    replace: "const isFree = mode.kind === 'free';",
    caseIds: ['docking.takeoff.grace', 'docking.takeoff.grace.autopilot'],
  },
  {
    id: 'takeoff.grace-blocks-target',
    file: DOCKING,
    find: 'if (isFree || isTarget) {',
    replace: 'if ((isFree || isTarget) && !grace) {',
    caseIds: ['docking.takeoff.grace.autopilot'],
  },
  {
    id: 'takeoff.grace-not-set',
    file: DOCKING,
    find: '    state.mode = freeMode();\n    state.takeOff = takeOffPoint(plane);',
    replace: '    state.mode = freeMode();',
    caseIds: ['docking.takeoff', 'docking.takeoff.grace'],
  },
  {
    id: 'takeoff.grace-not-set-on-autopilot',
    file: DOCKING,
    find: "    events.push({ type: 'undocked', station: mode.station });\n    state.takeOff = takeOffPoint(plane);",
    replace: "    events.push({ type: 'undocked', station: mode.station });",
    caseIds: ['docking.takeoff.grace.autopilot'],
  },
  {
    id: 'takeoff.grace-never-released',
    file: DOCKING,
    find: '  state.takeOff = null;\n\n  return false;',
    replace: '  return false;',
    caseIds: ['docking.takeoff.grace.released'],
  },
  {
    id: 'takeoff.point-aliased',
    file: DOCKING,
    find: 'return { x: plane.pos.x, y: plane.pos.y, z: plane.pos.z };',
    replace: 'return plane.pos;',
    caseIds: ['docking.takeoff'],
  },
  {
    id: 'cooldown.released-in-grace',
    file: DOCKING,
    find: 'if (!grace && distance > UNLINK_RANGE) {',
    replace: 'if (distance > UNLINK_RANGE) {',
    caseIds: ['docking.takeoff.grace.home-cooldown'],
  },
  {
    id: 'reset.keeps-takeoff',
    file: DOCKING,
    find: '  state.cooldown = 0;\n  state.takeOff = null;\n',
    replace: '  state.cooldown = 0;\n',
    caseIds: ['docking.reset'],
  },
  {
    id: 'dock.neighbour-ignored',
    file: DOCKING,
    find: 'if (bestClearance >= DOCK_NEIGHBOUR_CLEARANCE) {',
    replace: 'if (bestClearance >= 0) {',
    caseIds: ['docking.dock-point.neighbour', 'docking.dock-point.neighbour-margin'],
  },
  {
    id: 'dock.neighbour-margin',
    file: CONSTANTS,
    find: 'DOCK_NEIGHBOUR_MARGIN = 3',
    replace: 'DOCK_NEIGHBOUR_MARGIN = 2',
    caseIds: ['docking.dock-point.neighbour-margin'],
  },
  {
    id: 'dock.neighbour-self',
    file: DOCKING,
    find: '    if (other !== index) {',
    replace: '    if (other >= 0) {',
    caseIds: [
      'docking.dock-point.degenerate',
      'docking.dock-point.neighbour-margin',
      'docking.dock-point.crowded',
    ],
  },
  {
    id: 'dock.bearings-count',
    file: CONSTANTS,
    find: 'DOCK_BEARINGS = 8',
    replace: 'DOCK_BEARINGS = 4',
    caseIds: ['docking.dock-point.neighbour-margin'],
  },
  {
    id: 'dock.turn-order',
    file: DOCKING,
    find: '(turn + 1) / 2 : -turn / 2',
    replace: '-(turn + 1) / 2 : turn / 2',
    caseIds: ['docking.dock-point.neighbour-margin'],
  },
  {
    id: 'dock.rotation-mirrored',
    file: DOCKING,
    find: '    const x = ux * cos - uz * sin;\n    const z = ux * sin + uz * cos;',
    replace: '    const x = ux * cos + uz * sin;\n    const z = uz * cos - ux * sin;',
    caseIds: ['docking.dock-point.neighbour-margin'],
  },
  {
    id: 'dock.first-clear-ignored',
    file: DOCKING,
    find: '    if (clearance >= DOCK_NEIGHBOUR_CLEARANCE) {\n      return { x, z };\n    }\n',
    replace: '',
    caseIds: ['docking.dock-point.neighbour-margin'],
  },
  {
    id: 'dock.fallback-not-farthest',
    file: DOCKING,
    find: 'if (clearance > bestClearance) {',
    replace: 'if (clearance < bestClearance) {',
    caseIds: ['docking.dock-point.crowded'],
  },
];
